error reporting and gui mode

diff --git a/bin/infinity-ijobs-launch b/bin/infinity-ijobs-launch
--- a/bin/infinity-ijobs-launch
+++ b/bin/infinity-ijobs-launch
@@ -11,36 +11,36 @@ echo "# ========================================================================
 
 # are we on main node?
 if [ "`hostname -f`" != "${INF_MAIN_NODE}" ]; then
-    echo ""
-    echo " >>> ERROR: This script can be run only on the main computational node!"
-    echo "            Main node : ${INF_MAIN_NODE}"
-    echo "            Hostname  : `hostname -f`"
-    echo ""
+    echo "" >&2
+    echo " >>> ERROR: This script can be run only on the main computational node!" >&2
+    echo "            Main node : ${INF_MAIN_NODE}" >&2
+    echo "            Hostname  : `hostname -f`" >&2
+    echo "" >&2
     exit 1
 fi
 
 # we need access to main info file
 INF_INFOFILE="$INF_WORK_DIR/${INF_WHOLE_NAME}.info"
 if ! [ -f "$INF_INFOFILE" ]; then
-    echo ""
-    echo " >>> ERROR: Main job info file ($INF_INFOFILE) does not exist!"
-    echo ""
+    echo "" >&2
+    echo " >>> ERROR: Main job info file ($INF_INFOFILE) does not exist!" >&2
+    echo "" >&2
     exit 1
 fi
 
 # get number of ijobs
 NIJOBS="`$ABS_ROOT/sbin/abs-ijobs "$INF_INFOFILE" number`"
 if [ $? -ne 0 ]; then
-    echo ""
-    echo " >>> ERROR: Unable to get number of ijobs!"
-    echo ""
+    echo "" >&2
+    echo " >>> ERROR: Unable to get number of ijobs!" >&2
+    echo "" >&2
     exit 1
 fi
 
 if [ "$NIJOBS" -le 0 ]; then
-    echo ""
-    echo " >>> ERROR: No ijobs detected in the main job!"
-    echo ""
+    echo "" >&2
+    echo " >>> ERROR: No ijobs detected in the main job!" >&2
+    echo "" >&2
     exit 1
 fi
 
@@ -51,9 +51,9 @@ echo
 for((ID=1;ID<=$NIJOBS;ID++)); do
     INF_IJOB_ID="`$ABS_ROOT/sbin/abs-ijobs --id "$ID" "$INF_INFOFILE" id`"
     if [ $? -ne 0 ]; then
-        echo ""
-        echo " >>> ERROR: Unable to get id of ijob $ID!"
-        echo ""
+        echo "" >&2
+        echo " >>> ERROR: Unable to get id of ijob $ID!" >&2
+        echo "" >&2
         exit 1
     fi
 
@@ -61,23 +61,23 @@ for((ID=1;ID<=$NIJOBS;ID++)); do
 
     INF_IJOB_MAIN_NODE="`$ABS_ROOT/sbin/abs-ijobs --id "$ID" "$INF_INFOFILE" mainnode`"
     if [ $? -ne 0 ]; then
-        echo ""
-        echo " >>> ERROR: Unable to get mainnode of ijob $ID!"
-        echo ""
+        echo "" >&2
+        echo " >>> ERROR: Unable to get mainnode of ijob $ID!" >&2
+        echo "" >&2
         exit 1
     fi
     INF_IJOB_WORK_DIR="`$ABS_ROOT/sbin/abs-ijobs --id "$ID" "$INF_INFOFILE" workdir`"
     if [ $? -ne 0 ]; then
-        echo ""
-        echo " >>> ERROR: Unable to get workdir of ijob $ID!"
-        echo ""
+        echo "" >&2
+        echo " >>> ERROR: Unable to get workdir of ijob $ID!" >&2
+        echo "" >&2
         exit 1
     fi
     INF_IJOB_NAME="`$ABS_ROOT/sbin/abs-ijobs --id "$ID" "$INF_INFOFILE" name`"
     if [ $? -ne 0 ]; then
-        echo ""
-        echo " >>> ERROR: Unable to get name of ijob $ID!"
-        echo ""
+        echo "" >&2
+        echo " >>> ERROR: Unable to get name of ijob $ID!" >&2
+        echo "" >&2
         exit 1
     fi
     INF_TECH_OUTPUT="$INF_WORK_DIR/${INF_IJOB_ID}.infout"
diff --git a/bin/infinity-ijobs-prepare b/bin/infinity-ijobs-prepare
--- a/bin/infinity-ijobs-prepare
+++ b/bin/infinity-ijobs-prepare
@@ -10,44 +10,44 @@ echo "# ========================================================================
 
 # are we on main node?
 if [ "`hostname -f`" != "${INF_MAIN_NODE}" ]; then
-    echo ""
-    echo " >>> ERROR: This script can be run only on the main computational node!"
-    echo "            Main node : ${INF_MAIN_NODE}"
-    echo "            Hostname  : `hostname -f`"
-    echo ""
+    echo "" >&2
+    echo " >>> ERROR: This script can be run only on the main computational node!" >&2
+    echo "            Main node : ${INF_MAIN_NODE}" >&2
+    echo "            Hostname  : `hostname -f`" >&2
+    echo "" >&2
     exit 1
 fi
 
 # we need access to main info file
 INF_INFOFILE="$INF_WORK_DIR/${INF_WHOLE_NAME}.info"
 if ! [ -f "$INF_INFOFILE" ]; then
-    echo ""
-    echo " >>> ERROR: Main job info file ($INF_INFOFILE) does not exist!"
-    echo ""
+    echo "" >&2
+    echo " >>> ERROR: Main job info file ($INF_INFOFILE) does not exist!" >&2
+    echo "" >&2
     exit 1
 fi
 
 INF_NODEFILE="$INF_WORK_DIR/${INF_WHOLE_NAME}.nodes"
 if ! [ -f "$INF_NODEFILE" ]; then
-    echo ""
-    echo " >>> ERROR: Main node file ($INF_NODEFILE) does not exist!"
-    echo ""
+    echo "" >&2
+    echo " >>> ERROR: Main node file ($INF_NODEFILE) does not exist!" >&2
+    echo "" >&2
     exit 1
 fi
 
 # get number of ijobs
 NIJOBS="`$ABS_ROOT/sbin/abs-ijobs "$INF_INFOFILE" number`"
 if [ $? -ne 0 ]; then
-    echo ""
-    echo " >>> ERROR: Unable to get number of ijobs!"
-    echo ""
+    echo "" >&2
+    echo " >>> ERROR: Unable to get number of ijobs!" >&2
+    echo "" >&2
     exit 1
 fi
 
 if [ "$NIJOBS" -le 0 ]; then
-    echo ""
-    echo " >>> ERROR: No ijobs detected in the main job!"
-    echo ""
+    echo "" >&2
+    echo " >>> ERROR: No ijobs detected in the main job!" >&2
+    echo "" >&2
     exit 1
 fi
 
@@ -66,17 +66,17 @@ for((ID=1;ID<=$NIJOBS;ID++)); do
     # set working directory, master node, and node file ------------------------
     INF_IJOB_PATH=`$ABS_ROOT/sbin/abs-ijobs --id "$ID" "$INF_INFOFILE" path`
     if [ $? -ne -0 ]; then
-        echo ""
-        echo " >>> ERROR: Unable to get path for ijob $ID!"
-        echo ""
+        echo "" >&2
+        echo " >>> ERROR: Unable to get path for ijob $ID!" >&2
+        echo "" >&2
         exit 1
     fi
 
     INF_IJOB_NAME=`$ABS_ROOT/sbin/abs-ijobs --id "$ID" "$INF_INFOFILE" name`
     if [ $? -ne -0 ]; then
-        echo ""
-        echo " >>> ERROR: Unable to get name for ijob $ID!"
-        echo ""
+        echo "" >&2
+        echo " >>> ERROR: Unable to get name for ijob $ID!" >&2
+        echo "" >&2
         exit 1
     fi
 
@@ -85,8 +85,8 @@ for((ID=1;ID<=$NIJOBS;ID++)); do
             INF_IJOB_WORK_DIR="$INF_JOB_PATH/$INF_IJOB_PATH"
             if [ "$INF_REMOTE_JOBDIR" == "YES" ]; then
                 echo "" >&2
-                echo " ERROR: The job input directory must be available locally on the computational node" >&2
-                echo "        if the 'jobdir' synchronization mode is used!" >&2
+                echo " >>> ERROR: The job input directory must be available locally on the computational node" >&2
+                echo "            if the 'jobdir' synchronization mode is used!" >&2
                 echo "" >&2
                 return 1
             fi
@@ -94,9 +94,9 @@ for((ID=1;ID<=$NIJOBS;ID++)); do
         sync | nosync )
             SCRATCH_DIR="`$ABS_ROOT/sbin/abs-get-scratch-dir --type ijob $INF_SCRATCH_TYPE`"
             if [ $? -ne -0 ]; then
-                echo ""
-                echo " >>> ERROR: Unable to get ijob scratch dir!"
-                echo ""
+                echo "" >&2
+                echo " >>> ERROR: Unable to get ijob scratch dir!" >&2
+                echo "" >&2
                 exit 1
             fi
             echo "     Scratch dir definition   : $SCRATCH_DIR"
@@ -108,9 +108,9 @@ for((ID=1;ID<=$NIJOBS;ID++)); do
     INF_IJOB_MAIN_NODE=`head -$NCPU $INF_NODEFILE | tail -1`
     RNCPU=`$ABS_ROOT/sbin/abs-ijobs --id "$ID" "$INF_INFOFILE" ncpus`
     if [ $? -ne 0 ]; then
-        echo ""
-        echo " >>> ERROR: Unable to get number of cpus for ijob $ID!"
-        echo ""
+        echo "" >&2
+        echo " >>> ERROR: Unable to get number of cpus for ijob $ID!" >&2
+        echo "" >&2
         exit 1
     fi
     echo "     Requested number of CPUs : $RNCPU"
@@ -125,23 +125,23 @@ for((ID=1;ID<=$NIJOBS;ID++)); do
     # update info file ---------------------------------------------------------
     $ABS_ROOT/sbin/abs-ijobs --id "$ID" "$INF_INFOFILE" id --set "$INF_IJOB_ID"
     if [ $? -ne 0 ]; then
-        echo ""
-        echo " >>> ERROR: Unable to set ID of ijob $ID!"
-        echo ""
+        echo "" >&2
+        echo " >>> ERROR: Unable to set ID of ijob $ID!" >&2
+        echo "" >&2
         exit 1
     fi
     $ABS_ROOT/sbin/abs-ijobs --id "$ID" "$INF_INFOFILE" mainnode --set "$INF_IJOB_MAIN_NODE"
     if [ $? -ne 0 ]; then
-        echo ""
-        echo " >>> ERROR: Unable to set main node $INF_INODE_MAIN_NODE for ijob $INF_ID!"
-        echo ""
+        echo "" >&2
+        echo " >>> ERROR: Unable to set main node $INF_INODE_MAIN_NODE for ijob $INF_ID!" >&2
+        echo "" >&2
         exit 1
     fi
     $ABS_ROOT/sbin/abs-ijobs --id "$ID" "$INF_INFOFILE" workdir --set "$INF_IJOB_WORK_DIR"
     if [ $? -ne 0 ]; then
-        echo ""
-        echo " >>> ERROR: Unable to set main node $INF_INODE_MAIN_NODE for ijob $INF_ID!"
-        echo ""
+        echo "" >&2
+        echo " >>> ERROR: Unable to set main node $INF_INODE_MAIN_NODE for ijob $INF_ID!" >&2
+        echo "" >&2
         exit 1
     fi
 
@@ -164,7 +164,7 @@ for((ID=1;ID<=$NIJOBS;ID++)); do
 
                 if [ $? -ne 0 ]; then
                     echo "" >&2
-                    echo " ERROR: Unable to create the working directory on the specified node!" >&2
+                    echo " >>> ERROR: Unable to create the working directory on the specified node!" >&2
                     echo "" >&2
                     return 1
                 fi
@@ -184,7 +184,7 @@ for((ID=1;ID<=$NIJOBS;ID++)); do
 
                 if [ $? -ne 0 ]; then
                     echo "" >&2
-                    echo " ERROR: Unable to copy the input job data to the ijob main computational node!" >&2
+                    echo " >>> ERROR: Unable to copy the input job data to the ijob main computational node!" >&2
                     echo "" >&2
                     exit 1
                 fi
@@ -193,7 +193,7 @@ for((ID=1;ID<=$NIJOBS;ID++)); do
 
                 if [ $? -ne 0 ]; then
                     echo "" >&2
-                    echo " ERROR: Unable to copy the input job data to the ijob main computational node!" >&2
+                    echo " >>> ERROR: Unable to copy the input job data to the ijob main computational node!" >&2
                     echo "" >&2
                     exit 1
                 fi
@@ -207,7 +207,7 @@ for((ID=1;ID<=$NIJOBS;ID++)); do
 
                 if [ $? -ne 0 ]; then
                     echo "" >&2
-                    echo " ERROR: Unable to copy the input job data to theijob main computational node!" >&2
+                    echo " >>> ERROR: Unable to copy the input job data to theijob main computational node!" >&2
                     echo "" >&2
                     exit 1
                 fi
@@ -216,7 +216,7 @@ for((ID=1;ID<=$NIJOBS;ID++)); do
 
                 if [ $? -ne 0 ]; then
                     echo "" >&2
-                    echo " ERROR: Unable to copy the input job data to the ijob main computational node!" >&2
+                    echo " >>> ERROR: Unable to copy the input job data to the ijob main computational node!" >&2
                     echo "" >&2
                     exit 1
                 fi
diff --git a/bin/parchive b/bin/parchive
--- a/bin/parchive
+++ b/bin/parchive
@@ -58,7 +58,7 @@ function get_data_from_archive() {
 
     if [ $# -eq 0 ]; then
         echo "" 1>&2
-        echo ">>> ERROR: No files to get from the archive!" 1>&2
+        echo " >>> ERROR: No files to get from the archive!" 1>&2
         echo "" 1>&2
         return 1
     fi
@@ -67,7 +67,7 @@ function get_data_from_archive() {
 
     if [ $? -ne 0 ]; then
         echo "" 1>&2
-        echo ">>> ERROR: Unable to get specified data from the archive!" 1>&2
+        echo " >>> ERROR: Unable to get specified data from the archive!" 1>&2
         echo "" 1>&2
         exit 1
     fi
@@ -79,7 +79,7 @@ function write_to_archive() {
 
     if [ $# -eq 0 ]; then
         echo "" 1>&2
-        echo ">>> ERROR: No files to write to the archive!" 1>&2
+        echo " >>> ERROR: No files to write to the archive!" 1>&2
         echo "" 1>&2
         return 1
     fi
@@ -88,7 +88,7 @@ function write_to_archive() {
 
     if [ $? -ne 0 ]; then
         echo "" 1>&2
-        echo ">>> ERROR: Unable to get specified data from the archive!" 1>&2
+        echo " >>> ERROR: Unable to get specified data from the archive!" 1>&2
         echo "" 1>&2
         exit 1
     fi
@@ -100,7 +100,7 @@ function move_to_archive() {
 
     if [ $# -eq 0 ]; then
         echo "" 1>&2
-        echo ">>> ERROR: No files to move to the archive!" 1>&2
+        echo " >>> ERROR: No files to move to the archive!" 1>&2
         echo "" 1>&2
         return 1
     fi
@@ -126,12 +126,12 @@ case $1 in
         ;;
     * )
         echo "" 1>&2
-        echo ">>> ERROR: Unsupported action: $1" 1>&2
-        echo "           Supported action: runtime | get | write | move" 1>&2
-        echo "              parchive runtime <start> <current> <format>" 1>&2
-        echo "              parchive get   <file1> [file2] ..." 1>&2
-        echo "              parchive write <file1> [file2] ..." 1>&2
-        echo "              parchive move  <file1> [file2] ..." 1>&2
+        echo " >>> ERROR: Unsupported action: $1" 1>&2
+        echo "            Supported action: runtime | get | write | move" 1>&2
+        echo "                parchive runtime <start> <current> <format>" 1>&2
+        echo "                parchive get   <file1> [file2] ..." 1>&2
+        echo "                parchive write <file1> [file2] ..." 1>&2
+        echo "                parchive move  <file1> [file2] ..." 1>&2
         echo "" 1>&2
         exit 1
         ;;
@@ -149,14 +149,14 @@ if  [ -z "$INF_JOB_NAME" ] || [ -z "$INF_INPUT_MACHINE" ] || [ -z "$INF_INPUT_DI
     [ -z "$INF_SSH_OPTIONS" ] || [ -z "$INF_RETRY_COUNT" ] || \
     [ -z "$INF_RETRY_TIME" ] || [ -z "$INF_LOCAL_INPUT_DATA" ] || [ -z "$ABS_ROOT" ] || [ -z "$INF_ARCHIVE_DIR" ]; then
     echo "" 1>&2
-    echo ">>> ERROR: This command must be run in the Infinity environment!" 1>&2
+    echo " >>> ERROR: This command must be run in the Infinity environment!" 1>&2
     echo "" 1>&2
     exit 1
 fi
 
 if [ $# -eq 0 ]; then
     echo "" 1>&2
-    echo ">>> ERROR: No files are specified for archiving!" 1>&2
+    echo " >>> ERROR: No files are specified for archiving!" 1>&2
     echo "" 1>&2
     exit 1
 fi
diff --git a/share/scripts/abs-execution-script-L0 b/share/scripts/abs-execution-script-L0
--- a/share/scripts/abs-execution-script-L0
+++ b/share/scripts/abs-execution-script-L0
@@ -59,7 +59,7 @@ echo
 
 if ! [ -d "$ABS_ROOT" ]; then
     echo "" >&2
-    echo " ERROR: The ABS_ROOT directory does not exist!" >&2
+    echo " >>> ERROR: The ABS_ROOT directory does not exist!" >&2
     echo "" >&2
     exit 1
 fi
@@ -84,8 +84,8 @@ site -v activate "$INF_SITE_ID"
 
 if [ $? -ne 0 ]; then
     echo "" >&2
-    echo " ERROR: Unable to activate the site ($INF_SITE_ID)!" >&2
-    echo "        Please send contents of this output to the site support: $AMS_SITE_SUPPORT" >&2
+    echo " >>> ERROR: Unable to activate the site ($INF_SITE_ID)!" >&2
+    echo "            Please send contents of this output to the site support: $AMS_SITE_SUPPORT" >&2
     echo "" >&2
     exit 1
 fi
@@ -97,8 +97,8 @@ amsmodule --system add abs:$INF_ABS_VERSION
 
 if [ $? -ne 0 ]; then
     echo "" >&2
-    echo " ERROR: Unable to add the 'abs:$INF_ABS_VERSION' module!" >&2
-    echo "        Please send contents of this output to the site support: $AMS_SITE_SUPPORT" >&2
+    echo " >>> ERROR: Unable to add the 'abs:$INF_ABS_VERSION' module!" >&2
+    echo "            Please send contents of this output to the site support: $AMS_SITE_SUPPORT" >&2
     echo "" >&2
     exit 1
 fi
@@ -110,16 +110,16 @@ amsmodule --system add abs-rsync
 
 if [ $? -ne 0 ]; then
     echo "" >&2
-    echo " ERROR: Unable to add the 'abs-rsync' module!" >&2
-    echo "        Please send contents of this output to the site support: $AMS_SITE_SUPPORT" >&2
+    echo " >>> ERROR: Unable to add the 'abs-rsync' module!" >&2
+    echo "            Please send contents of this output to the site support: $AMS_SITE_SUPPORT" >&2
     echo "" >&2
     exit 1
 fi
 
 if ! [ -e "$ABS_RSYNC" ]; then
     echo "" >&2
-    echo " ERROR: '$ABS_RSYNC' is not executable!" >&2
-    echo "        Please send contents of this output to the site support: $AMS_SITE_SUPPORT" >&2
+    echo " >>> ERROR: '$ABS_RSYNC' is not executable!" >&2
+    echo "            Please send contents of this output to the site support: $AMS_SITE_SUPPORT" >&2
     echo "" >&2
     exit 1
 fi
diff --git a/share/scripts/abs-execution-script-L2 b/share/scripts/abs-execution-script-L2
--- a/share/scripts/abs-execution-script-L2
+++ b/share/scripts/abs-execution-script-L2
@@ -42,7 +42,7 @@ if [ "$INF_LOCAL_INPUT_DATA" == "YES" ]; then
     if [ -n "$INF_LR" ]; then
         if [ "$INF_LR" != "$INF_STORAGE_MACHINE_REALM" ]; then
             echo "" >&2
-            echo " ERROR: The local input directory realm '$INF_LR' does not match the storage machine realm '$INF_STORAGE_MACHINE_REALM'!" >&2
+            echo " >>> ERROR: The local input directory realm '$INF_LR' does not match the storage machine realm '$INF_STORAGE_MACHINE_REALM'!" >&2
             echo "" >&2
             exit 1
         fi
@@ -136,7 +136,7 @@ case $INF_DATAIN in
 
             if [ $? -ne 0 ]; then
                 echo "" >&2
-                echo " ERROR: Unable to create the working directory on the specified node!" >&2
+                echo " >>> ERROR: Unable to create the working directory on the specified node!" >&2
                 echo "" >&2
                 exit 1
             fi
@@ -154,7 +154,7 @@ cd "$INF_WORK_DIR"
 
 if [ $? -ne 0 ]; then
     echo "" >&2
-    echo " ERROR: Unable to change the current directory to the working directory." >&2
+    echo " >>> ERROR: Unable to change the current directory to the working directory." >&2
     echo "" >&2
     exit 1
 fi
@@ -165,7 +165,7 @@ fi
 mv "$TMPDIR/${_TNAME_}.info" "$INF_WORK_DIR/${INF_WHOLE_NAME}.info"
 if [ $? -ne 0 ]; then
     echo "" >&2
-    echo " ERROR: Unable to move the job info file into the working directory!" >&2
+    echo " >>> ERROR: Unable to move the job info file into the working directory!" >&2
     echo "" >&2
     exit 1
 fi
@@ -181,7 +181,7 @@ echo "# File: $PBS_NODEFILE"
 
 if ! [ -f "$PBS_NODEFILE" ]; then
     echo ""  >&2
-    echo " ERROR: PBS_NODEFILE does not exist!"  >&2
+    echo " >>> ERROR: PBS_NODEFILE does not exist!"  >&2
     echo "" >&2
     exit 1
 fi
@@ -241,7 +241,7 @@ echo "# Write the job start and update the info file in the input directory ..."
 $ABS_ROOT/sbin/abs-update-infofile start
 if [ $? -ne 0 ]; then
     echo "" >&2
-    echo " ERROR: Unable to update job status in the job info file!" >&2
+    echo " >>> ERROR: Unable to update job status in the job info file!" >&2
     echo "" >&2
     exit 1
 fi
diff --git a/share/scripts/abs-execution-script-L4 b/share/scripts/abs-execution-script-L4
--- a/share/scripts/abs-execution-script-L4
+++ b/share/scripts/abs-execution-script-L4
@@ -31,8 +31,8 @@ case $INF_JOB_NAME in
         amsmodule add screen
         if [ $? -ne 0 ]; then
             echo "" >&2
-            echo " ERROR: Unable to add the 'screen' module!" >&2
-            echo "        Please send contents of this output to the site support: $AMS_SITE_SUPPORT" >&2
+            echo " >>> ERROR: Unable to add the 'screen' module!" >&2
+            echo "            Please send contents of this output to the site support: $AMS_SITE_SUPPORT" >&2
             echo "" >&2
             exit 1
         fi
@@ -58,7 +58,7 @@ case $INF_JOB_NAME in
 
         if [ $? -ne 0 ]; then
             echo "" >&2
-            echo " ERROR: Unable to update job status in the job info file!" >&2
+            echo " >>> ERROR: Unable to update job status in the job info file!" >&2
             echo "" >&2
             kill $SCREEN_PID
             return 1
@@ -91,8 +91,8 @@ case $INF_JOB_NAME in
         amsmodule add tigervnc
         if [ $? -ne 0 ]; then
             echo "" >&2
-            echo " ERROR: Unable to add the 'tigervnc' module!" >&2
-            echo "        Please send contents of this output to the site support: $AMS_SITE_SUPPORT" >&2
+            echo " >>> ERROR: Unable to add the 'tigervnc' module!" >&2
+            echo "            Please send contents of this output to the site support: $AMS_SITE_SUPPORT" >&2
             echo "" >&2
             exit 1
         fi
@@ -101,7 +101,7 @@ case $INF_JOB_NAME in
         touch "$INF_WORK_DIR/${INF_WHOLE_NAME}.vncpsw"
         if [ $? -ne 0 ]; then
             echo "" >&2
-            echo " ERROR: Unable to create VNC password file '$INF_WORK_DIR/${INF_WHOLE_NAME}.vncpsw'!" >&2
+            echo " >>> ERROR: Unable to create VNC password file '$INF_WORK_DIR/${INF_WHOLE_NAME}.vncpsw'!" >&2
             echo "" >&2
             exit 1
         fi
@@ -109,7 +109,7 @@ case $INF_JOB_NAME in
         uuidgen | vncpasswd -f > "$INF_WORK_DIR/${INF_WHOLE_NAME}.vncpsw"
 
         # start VNC server
-        vncserver -fg -rfbauth "$INF_WORK_DIR/${INF_WHOLE_NAME}.vncpsw"  > "$INF_WORK_DIR/${INF_WHOLE_NAME}.vnclog" &
+        vncserver -fg -rfbauth "$INF_WORK_DIR/${INF_WHOLE_NAME}.vncpsw" &> "$INF_WORK_DIR/${INF_WHOLE_NAME}.vnclog" &
 
         VNCSERVER_PID=$!
 
@@ -123,7 +123,7 @@ case $INF_JOB_NAME in
 
         if [ -z "$INF_VNC_ID" ]; then
             echo "" >&2
-            echo " ERROR: Unable to get VNC ID from the log file '$INF_WORK_DIR/${INF_WHOLE_NAME}.vnclog'!" >&2
+            echo " >>> ERROR: Unable to get VNC ID from the log file '$INF_WORK_DIR/${INF_WHOLE_NAME}.vnclog'!" >&2
             kill $VNCSERVER_PID
             echo "" >&2
             exit 1
@@ -133,7 +133,7 @@ case $INF_JOB_NAME in
 
         if [ $? -ne 0 ]; then
             echo "" >&2
-            echo " ERROR: Unable to update job status in the job info file!" >&2
+            echo " >>> ERROR: Unable to update job status in the job info file!" >&2
             kill $VNCSERVER_PID
             echo "" >&2
             return 1
diff --git a/share/scripts/abs-execution-script-L5 b/share/scripts/abs-execution-script-L5
--- a/share/scripts/abs-execution-script-L5
+++ b/share/scripts/abs-execution-script-L5
@@ -49,7 +49,7 @@ echo "# Write the job end and update the info file in the input directory ..."
 $ABS_ROOT/sbin/abs-update-infofile stop
 if [ $? -ne 0 ]; then
     echo "" >&2
-    echo " ERROR: Unable to update the job status in the job info file!" >&2
+    echo " >>> ERROR: Unable to update the job status in the job info file!" >&2
     echo "" >&2
     exit 1
 fi
diff --git a/share/scripts/abs-execution-script-L6-ijobs b/share/scripts/abs-execution-script-L6-ijobs
--- a/share/scripts/abs-execution-script-L6-ijobs
+++ b/share/scripts/abs-execution-script-L6-ijobs
@@ -10,18 +10,18 @@ INF_NODEFILE="$INF_WORK_DIR/${INF_WHOLE_NAME}.nodes"
 # get number of ijobs
 NIJOBS="`$ABS_ROOT/sbin/abs-ijobs "$INF_INFOFILE" number`"
 if [ $? -ne 0 ]; then
-    echo ""
-    echo " >>> ERROR: Unable to get number of ijobs!"
-    echo ""
+    echo "" >&2
+    echo " >>> ERROR: Unable to get number of ijobs!" >&2
+    echo "" >&2
     exit 1
 fi
 
 for((ID=1;ID<=$NIJOBS;ID++)); do
     INF_IJOB_ID="`$ABS_ROOT/sbin/abs-ijobs --id "$ID" "$INF_INFOFILE" id`"
     if [ $? -ne 0 ]; then
-        echo ""
-        echo " >>> ERROR: Unable to get id of ijob $ID!"
-        echo ""
+        echo "" >&2
+        echo " >>> ERROR: Unable to get id of ijob $ID!" >&2
+        echo "" >&2
         exit 1
     fi
 
@@ -30,23 +30,23 @@ for((ID=1;ID<=$NIJOBS;ID++)); do
 
     INF_IJOB_MAIN_NODE="`$ABS_ROOT/sbin/abs-ijobs --id "$ID" "$INF_INFOFILE" mainnode`"
     if [ $? -ne 0 ]; then
-        echo ""
-        echo " >>> ERROR: Unable to get mainnode of ijob $ID!"
-        echo ""
+        echo "" >&2
+        echo " >>> ERROR: Unable to get mainnode of ijob $ID!" >&2
+        echo "" >&2
         exit 1
     fi
     INF_IJOB_WORK_DIR="`$ABS_ROOT/sbin/abs-ijobs --id "$ID" "$INF_INFOFILE" workdir`"
     if [ $? -ne 0 ]; then
-        echo ""
-        echo " >>> ERROR: Unable to get workdir of ijob $ID!"
-        echo ""
+        echo "" >&2
+        echo " >>> ERROR: Unable to get workdir of ijob $ID!" >&2
+        echo "" >&2
         exit 1
     fi
     INF_IJOB_NODEFILE="$INF_WORK_DIR/${INF_IJOB_ID}.nodes"
     if ! [ -f "$INF_IJOB_NODEFILE" ]; then
-        echo ""
-        echo " >>> ERROR: ijob node file ($INF_IJOB_NODEFILE) does not exist!"
-        echo ""
+        echo "" >&2
+        echo " >>> ERROR: ijob node file ($INF_IJOB_NODEFILE) does not exist!" >&2
+        echo "" >&2
         exit 1
     fi
 
diff --git a/share/scripts/abs-go b/share/scripts/abs-go
--- a/share/scripts/abs-go
+++ b/share/scripts/abs-go
@@ -46,10 +46,10 @@ case "$INF_GO_JOB_NAME" in
                 echo "          Hostname     : $HOSTNAME"
             fi
             if ! [ -d "$INF_GO_INPUT_DIR" ]; then
-                echo ""
-                echo " ERROR: The job input directory does not exist on this host!"
-                echo "        $INF_GO_INPUT_DIR"
-                echo ""
+                echo "" >&2
+                echo " >>> ERROR: The job input directory does not exist on this host!" >&2
+                echo "            $INF_GO_INPUT_DIR" >&2
+                echo "" >&2
                 return 1
             fi
             cd "$INF_GO_INPUT_DIR"
diff --git a/share/scripts/abs-go-remote b/share/scripts/abs-go-remote
--- a/share/scripts/abs-go-remote
+++ b/share/scripts/abs-go-remote
@@ -33,24 +33,24 @@ fi
 
 site activate $INF_SITE_ID 2> /dev/null
 if [ $? -ne 0 ]; then
-    echo " ERROR: Site ($INF_SITE_ID) cannot be activated!"
-    echo
+    echo " >>> ERROR: The site ($INF_SITE_ID) cannot be activated!" >&2
+    echo >&2
     exit 1
 fi
 
 if [ "$AMS_ALTERNATIVE_BOOT" == "YES" ]; then
-    echo ">>> NOTE: Infinity has been booted using an alternative approach,"
-    echo "          please report this to the site support: $AMS_SITE_SUPPORT"
-    echo "          (Include the whole output beggining by the pgo command!)"
+    echo " >>> NOTE: Infinity has been booted using an alternative approach,"
+    echo "           please report this to the site support: $AMS_SITE_SUPPORT"
+    echo "           (Include the whole output beggining by the pgo command!)"
     echo ""
-    echo "          In the alternative mode, some functionality might be limited!"
+    echo "           In the alternative mode, some functionality might be limited!"
     echo ""
 fi
 
 cd $INF_WORK_DIR 2> /dev/null
 if [ $? -ne 0 ]; then
-    echo " ERROR: Job working directory ($INF_WORK_DIR) is not accesible!"
-    echo
+    echo " >>> ERROR: The job working directory ($INF_WORK_DIR) is not accesible!" >&2
+    echo >&2
     exit 1
 fi
 if [ -n "$INF_SITE_EMODS" ]; then
diff --git a/share/scripts/abs-sync b/share/scripts/abs-sync
--- a/share/scripts/abs-sync
+++ b/share/scripts/abs-sync
@@ -28,14 +28,14 @@ amsmodule --system add abs-rsync 2> /dev/null
 
 if [ $? -ne 0 ]; then
     echo "" >&2
-    echo " ERROR: Unable to add the 'abs-rsync' module!" >&2
+    echo " >>> ERROR: Unable to add the 'abs-rsync' module!" >&2
     echo "" >&2
     exit 1
 fi
 
 if ! [ -e "$ABS_RSYNC" ]; then
     echo "" >&2
-    echo " ERROR: '$ABS_RSYNC' is not executable!" >&2
+    echo " >>> ERROR: '$ABS_RSYNC' is not executable!" >&2
     echo "" >&2
     exit 1
 fi
@@ -57,9 +57,9 @@ if [ "$INF_SYNC_ALL" == "YES" ]; then
               --rsync-path="LOC_RSYNC=rsync; if [ -f $ABS_RSYNC ]; then LOC_RSYNC=$ABS_RSYNC; fi; \$LOC_RSYNC" \
               "$INF_SYNC_WORK_DIR/" "$INF_SYNC_INPUT_MACHINE:$INF_SYNC_INPUT_DIR/" 2>&1 | awk '{ printf("   %s\n",$0); }'
         if [ $? -ne 0 ]; then
-            echo ""
-            echo " ERROR: Unable to copy all files!"
-            echo ""
+            echo "" >&2
+            echo " >>> ERROR: Unable to copy all files!" >&2
+            echo "" >&2
             exit 1
         fi
     else
@@ -68,9 +68,9 @@ if [ "$INF_SYNC_ALL" == "YES" ]; then
               --rsync-path="LOC_RSYNC=rsync; if [ -f $ABS_RSYNC ]; then LOC_RSYNC=$ABS_RSYNC; fi; \$LOC_RSYNC" \
               "$INF_SYNC_MAIN_NODE:$INF_SYNC_WORK_DIR/" "$INF_SYNC_INPUT_DIR/" 2>&1 | awk '{ printf("   %s\n",$0); }'
         if [ $? -ne 0 ]; then
-            echo ""
-            echo " ERROR: Unable to copy all files!"
-            echo ""
+            echo "" >&2
+            echo " >>> ERROR: Unable to copy all files!" >&2
+            echo "" >&2
             exit 1
         fi
     fi
@@ -102,9 +102,9 @@ else
 fi
 
 if [ "$FILES" == "" ]; then
-    echo ""
-    echo " ERROR: No files were specified ..."
-    echo ""
+    echo "" >&2
+    echo " >>> ERROR: No files were specified ..." >&2
+    echo "" >&2
     exit 1
 fi
 
@@ -120,9 +120,9 @@ for SFILE in $FILES; do
                   --rsync-path="LOC_RSYNC=rsync; if [ -f $ABS_RSYNC ]; then LOC_RSYNC=$ABS_RSYNC; fi; \$LOC_RSYNC" \
                   "$INF_SYNC_WORK_DIR/$SFILE" "$INF_SYNC_INPUT_MACHINE:$INF_SYNC_INPUT_DIR/" > /dev/null
             if [ $? -ne 0 ]; then
-                echo ""
-                echo " ERROR: Unable to copy the file!"
-                echo ""
+                echo "" >&2
+                echo " >>> ERROR: Unable to copy the file!" >&2
+                echo "" >&2
                 exit 1
             fi
         else
@@ -130,9 +130,9 @@ for SFILE in $FILES; do
                   --rsync-path="LOC_RSYNC=rsync; if [ -f $ABS_RSYNC ]; then LOC_RSYNC=$ABS_RSYNC; fi; \$LOC_RSYNC" \
                   "$INF_SYNC_MAIN_NODE:$INF_SYNC_WORK_DIR/$SFILE" "$INF_SYNC_INPUT_DIR/" > /dev/null
             if [ $? -ne 0 ]; then
-                echo ""
-                echo " ERROR: Unable to copy the file!"
-                echo ""
+                echo "" >&2
+                echo " >>> ERROR: Unable to copy the file!" >&2
+                echo "" >&2
                 exit 1
             fi
         fi
