psubmit

diff --git a/bin/presubmit b/bin/presubmit
--- a/bin/presubmit
+++ b/bin/presubmit
@@ -6,7 +6,7 @@
 
 if [ -z "$INF_ARG_DESTINATION" ] || [ -z "$INF_ARG_JOB" ]; then
     echo "" >&2
-    echo " >>> ERROR: INF_ARG_DESTINATION or INF_ARG_JOB variables are not set!" >&2
+    echo " >>> ERROR: The INF_ARG_DESTINATION or INF_ARG_JOB variables are not set!" >&2
     echo "            The job was not resubmited!" >&2
     echo "" >&2
     exit 1
@@ -14,7 +14,7 @@ fi
 
 if [ -z "$INF_INPUT_MACHINE" ] || [ -z "$INF_INPUT_DIR" ]; then
     echo "" >&2
-    echo " >>> ERROR: INF_INPUT_MACHINE or INF_INPUT_DIR variables are not set!" >&2
+    echo " >>> ERROR: The INF_INPUT_MACHINE or INF_INPUT_DIR variables are not set!" >&2
     echo "            The job was not resubmited!" >&2
     echo "" >&2
     exit 1
@@ -30,7 +30,7 @@ else
 fi
 
 # submit new run
-ssh -x -o "StrictHostKeyChecking=no" "$INF_INPUT_MACHINE" "
+ssh -x $INF_SSH_OPTIONS "$INF_INPUT_MACHINE" "
             if [ -f ~/.bash_profile ]; then source ~/.bash_profile; fi; \
             site activate $INF_SITE_ID; \
             module add abs:$INF_ABS_VERSION &> /dev/null; \
@@ -38,7 +38,7 @@ ssh -x -o "StrictHostKeyChecking=no" "$INF_INPUT_MACHINE" "
             cd \"$INF_INPUT_DIR\"; \
             export INF_EXTERNAL_START_AFTER=$INF_JOB_ID;
             export INF_EXTERNAL_NAME_SUFFIX=\"$INF_EXTERNAL_NAME_SUFFIX\";
-            psubmit -y -i \"$INF_ARG_DESTINATION\" \"$INF_ARG_JOB\" \"$INF_ARG_RESOURCES\"; "
+            psubmit -y -i -e -r \"$INF_ARG_DESTINATION\" \"$INF_ARG_JOB\" \"$INF_ARG_RESOURCES\"; "
 
 if [ $? -ne 0 ]; then
     echo "" >&2
