submit

diff --git a/share/scripts/abs-execution-script-L6 b/share/scripts/abs-execution-script-L6
--- a/share/scripts/abs-execution-script-L6
+++ b/share/scripts/abs-execution-script-L6
@@ -1,6 +1,7 @@
 #!/bin/bash
 # =============================================================================
 # ABS
+# (c) 2017, Petr Kulhanek, kulhanek@chemi.muni.cz
 # (c) 2008-2009, Petr Kulhanek, kulhanek@chemi.muni.cz
 # Charon Extension Layer v0.9
 # (c) 2006, Petr Kulhanek, kulhanek@chemi.muni.cz
@@ -22,9 +23,10 @@ pqstat -j "$INF_JOB_ID"
 
 echo ""
 echo "# ------------------------------------------------------------------------------"
-echo "# L6.2: Clean up ijobs nodes if any ..."
+echo "# L6.2: Cleaning up ijobs nodes if any ..."
 echo "# ------------------------------------------------------------------------------"
-echo " Data OUT copy mode : $INF_DATAOUT"
+echo "Working directory  : $INF_WORK_DIR"
+echo "Data OUT copy mode : $INF_DATAOUT"
 
 # get number of ijobs
 INF_INFOFILE="$INF_WORK_DIR/${INF_WHOLE_NAME}.info"
@@ -38,9 +40,10 @@ fi
 
 echo ""
 echo "# ------------------------------------------------------------------------------"
-echo "# L6.3: Clean up nodes ..."
+echo "# L6.3: Cleaning up nodes ..."
 echo "# ------------------------------------------------------------------------------"
-echo " Data OUT copy mode : $INF_DATAOUT"
+echo "Working directory  : $INF_WORK_DIR"
+echo "Data OUT copy mode : $INF_DATAOUT"
 
 # switch to HOME directory because next commands can remove current directory
 cd
@@ -48,28 +51,30 @@ cd
 CLEAN_DIR="`$ABS_ROOT/sbin/abs-get-work-dir --type clean $INF_WORK_DIR_TYPE`"
 if [ $? -ne -0 ]; then
     echo ""
-    echo " >>> ERROR: Unable to get clean scratch dir!"
+    echo " >>> ERROR: Unable to get the clean scratch directory path!"
     echo ""
     exit 1
 fi
 INF_CLEAN_DIR="`eval echo "$CLEAN_DIR"`"
 
+echo "Clean directory    : $INF_CLEAN_DIR"
+
 case $INF_DATAOUT in
     copy)
-        echo " Removing working directories on nodes ..."
+        echo "Removing working directories on nodes ..."
         for NODE_NAME in `cat $PBS_NODEFILE | sort -u`; do
             echo ""
             echo ">>> $NODE_NAME:$INF_CLEAN_DIR ---"
-            ssh -x -o "StrictHostKeyChecking=no" $NODE_NAME "timeout 30 df -h; if [ \$? -ne 0 ]; then echo \">>> WARNING: df command was not completed due to error or timeout.\"; fi; rm -rf $INF_CLEAN_DIR"
+            ssh -x -o "$INF_SSH_OPTIONS" $NODE_NAME "timeout 30 df -h; if [ \$? -ne 0 ]; then echo \">>> WARNING: the df command was not completed due to an error or timeout.\"; fi; rm -rf $INF_CLEAN_DIR"
         done
         ;;
     keep)
-        echo " No directories will be removed ..."
+        echo "No directories will be removed ..."
         echo ""
         echo ">>> $INF_MAIN_NODE ------------------------------"
         timeout 30 df -h
         if [ $? -ne 0 ]; then
-            echo ">>> WARNING: df command was not completed due to error or timeout."
+            echo ">>> WARNING: the df command was not completed due to an error or timeout."
         fi
         ;;
     esac
@@ -77,12 +82,11 @@ case $INF_DATAOUT in
 IPC_SCRIPT="$ABS_ROOT/share/scripts/abs-cleanipcs"
 if [ -f "$IPC_SCRIPT" ]; then
     echo ""
-    echo " Cleaning IPC stuff on nodes:"
+    echo "Cleaning IPC stuff on nodes:"
     for NODE_NAME in `cat $PBS_NODEFILE | sort -u`; do
         echo "      $NODE_NAME"
-        ssh -x -o "StrictHostKeyChecking=no" $NODE_NAME "$IPC_SCRIPT"
+        ssh -x -o "$INF_SSH_OPTIONS" $NODE_NAME "$IPC_SCRIPT"
     done
-    echo " Success."
 fi
 
 # ------------------------------------------------------------------------------
