various bugfixes and improvements RT#201538

diff --git a/share/scripts/abs-go b/share/scripts/abs-go
--- a/share/scripts/abs-go
+++ b/share/scripts/abs-go
@@ -48,15 +48,43 @@ case "$INF_GO_JOB_NAME" in
         ;;
     gui )
         if [ -n "$INF_GO_AGENT_MODULE" ] && [ -n "$INF_GO_VNC_ID" ] && [ -n "$INF_GO_WHOLE_NAME" ] ; then
-            amsmodule add "$INF_GO_AGENT_MODULE"
-            if [ $? -ne 0 ]; then
-                echo "" >&2
-                echo " >>> ERROR: Unable to activate a GUI agent module '$INF_GO_AGENT_MODULE'!" >&2
-                echo "" >&2
-                return 1
+            if [ "$INF_GO_GUI_PROXY" != "ssh-proxy" ]; then
+                amsmodule add "$INF_GO_AGENT_MODULE"
+                if [ $? -ne 0 ]; then
+                    echo "" >&2
+                    echo " >>> ERROR: Unable to activate a GUI agent module '$INF_GO_AGENT_MODULE'!" >&2
+                    echo "" >&2
+                    return 1
+                fi
+                vncviewer "$INF_GO_VNC_ID" -passwd "${INF_GO_WHOLE_NAME}.vncpsw"
+                return $?
+            else
+                echo -n " >>> INFO: Starting VNC proxy .... "
+                FREEPORT=0
+                set -o pipefail
+                for((PORT=1;PORT<=100;PORT++)); do
+                    netstat -lnp | grep 0.0.0.0:$((5900+$PORT)) &> /dev/null
+                    if [ $? -ne 0 ]; then
+                        FREEPORT=$PORT;
+                        break;
+                    fi
+                done
+                if [ "$FREEPORT" -eq 0 ]; then
+                    echo ""
+                    echo "" >&2
+                    echo " >>> ERROR: No available ports in the range <5901; 6000>!" >&2
+                    echo "" >&2
+                    return 1
+                fi
+                INF_REMOTE_NODE="`echo $cut -d ':' -f 1`"
+                INF_REMOTE_PORT="`echo $cut -d ':' -f 2`"
+                echo "`hostname -f`:$FREEPORT"
+                echo "              Password: `cat ${INF_GO_WHOLE_NAME}.vncpsw`"
+                echo ""
+                echo "              To terminate the proxy, press Enter."
+                ssh -L "$((5900+$FREEPORT)):0.0.0.0:$((5900+$INF_REMOTE_PORT))" "$INF_REMOTE_NODE" read
+                echo ""
             fi
-            vncviewer "$INF_GO_VNC_ID" -passwd "${INF_GO_WHOLE_NAME}.vncpsw"
-            return $?
         fi
         ;;
     * )
