pgo fix RT#213222

diff --git a/share/scripts/abs-go b/share/scripts/abs-go
--- a/share/scripts/abs-go
+++ b/share/scripts/abs-go
@@ -94,12 +94,20 @@ case "$INF_GO_JOB_NAME" in
                 echo "" >&2
                 return 1
             fi
+            echo ""
             cd "$INF_GO_INPUT_DIR"
-            echo ""
-            echo " INFO: The current directory was set to:"
-            echo "       $INF_GO_INPUT_DIR"
-            echo ""
-            return 0
+            if [ $? -eq 0 ]; then
+                echo " INFO: The current directory was set to:"
+                echo "       $INF_GO_INPUT_DIR"
+                echo ""
+                return 0
+            else
+                echo ""
+                echo " ERROR: Unable to set current directory to:"
+                echo "       $INF_GO_INPUT_DIR"
+                echo ""
+                return 1
+            fi
         fi
         ;;
 esac
diff --git a/share/scripts/abs-go-remote b/share/scripts/abs-go-remote
--- a/share/scripts/abs-go-remote
+++ b/share/scripts/abs-go-remote
@@ -49,7 +49,7 @@ fi
 
 cd $INF_WORK_DIR 2> /dev/null
 if [ $? -ne 0 ]; then
-    echo " >>> ERROR: The job working directory ($INF_WORK_DIR) is not accesible!" >&2
+    echo " >>> ERROR: The job working/input directory ($INF_WORK_DIR) is not accesible!" >&2
     echo >&2
     exit 1
 fi
