pgo, psync, pkill improvemetns

diff --git a/share/scripts/abs-execution-script-L4 b/share/scripts/abs-execution-script-L4
--- a/share/scripts/abs-execution-script-L4
+++ b/share/scripts/abs-execution-script-L4
@@ -12,6 +12,90 @@
 # (c) 2001-2004, Petr Kulhanek, kulhanek@chemi.muni.cz
 # =============================================================================
 
+function abs_write_kill_header()
+{
+cat << EOF
+#!/bin/bash
+# ********************************************************************
+# WARNING: This script will kill the job, use it with precaution!
+#*********************************************************************
+
+if [ "\$1" != "$INF_JOB_KEY" ]; then
+    echo >&2
+    echo " >>> ERROR: Unable to execute due to incorrect job key!" >&2
+    echo >&2
+    exit 1
+fi
+EOF
+}
+
+# ------------------------------------------------------------------------------
+
+function abs_write_kill_screen()
+{
+cat << EOF
+
+# activate site and terminal agent module
+site activate $INF_SITE_ID
+amsmodule add $INF_AGENT_MODULE
+
+# terminate screen session
+screen -d -r "T$INF_JOB_KEY -X quit
+EOF
+}
+
+# ------------------------------------------------------------------------------
+
+function abs_write_kill_tigervnc()
+{
+cat << EOF
+
+# activate site and terminal agent module
+site activate $INF_SITE_ID
+amsmodule add $INF_AGENT_MODULE
+
+# terminate vnc display
+vncserver -kill $INF_VNC_DISPLAY
+EOF
+}
+
+# ------------------------------------------------------------------------------
+
+function abs_write_kill_script()
+{
+cat << EOF
+
+# kill the main job process
+kill $MY_PID
+EOF
+}
+
+# ------------------------------------------------------------------------------
+
+function abs_write_kill_footer()
+{
+
+# wait until the session is terminated
+for((I=0;I<12;I++)); do
+    if ! [ -d /proc/$INF_AGENT_PID ]; then
+        exit
+    fi
+    echo ">>> INFO: Waiting until the agent session termination ...."
+    sleep 5
+done
+
+# if not terminated within 60 seconds - kill the process
+kill $INF_AGENT_PID
+sleep 5
+if ! [ -d /proc/$INF_AGENT_PID ]; then
+    exit
+fi
+kill -9 $INF_AGENT_PID
+EOF
+}
+
+# ------------------------------------------------------------------------------
+
 echo ""
 echo "# ------------------------------------------------------------------------------"
 echo "# L4: Starting the job ..."
@@ -37,6 +121,9 @@ case $INF_JOB_NAME in
             exit 1
         fi
 
+        INF_AGENT_MODULE="`amsmodule getactmod screen 2>&1`"
+        export INF_AGENT_MODULE
+
         # disable termcap capabilities
         export SCREENCAP=""
         # start screen terminal and detach from it
@@ -46,6 +133,19 @@ case $INF_JOB_NAME in
         # catch signals to properly terminate screen session
         trap "kill $SCREEN_PID; exit" SIGINT SIGTERM
 
+        # create kill script
+        touch "${INF_WHOLE_NAME}.kill"
+        if [ $? -ne 0 ]; then
+            echo "" >&2
+            echo " >>> ERROR: Unable to create kill script '${INF_WHOLE_NAME}.kill'!" >&2
+            echo "" >&2
+            exit 1
+        fi
+        chmod 600 "${INF_WHOLE_NAME}.kill"
+        abs_write_kill_header >  "${INF_WHOLE_NAME}.kill"
+        abs_write_kill_screen >> "${INF_WHOLE_NAME}.kill"
+        abs_write_kill_footer >> "${INF_WHOLE_NAME}.kill"
+
         # setup terminal
         sleep 10  # wait for terminal initialization
         screen -S "T$INF_JOB_KEY" -p 0 -X backtick 100 1 1 pinfo --terminal
@@ -54,8 +154,8 @@ case $INF_JOB_NAME in
         screen -S "T$INF_JOB_KEY" -p 0 -X log on
         screen -S "T$INF_JOB_KEY" -p 0 -X caption always
 
-        $ABS_ROOT/sbin/abs-update-infofile cliready
-
+        # update info file
+        $ABS_ROOT/sbin/abs-update-infofile --agent "$INF_AGENT_MODULE" cliready
         if [ $? -ne 0 ]; then
             echo "" >&2
             echo " >>> ERROR: Unable to update job status in the job info file!" >&2
@@ -84,7 +184,6 @@ case $INF_JOB_NAME in
             exit 1  # immediatelly exit
         fi
         echo "CLI terminal was terminated."
-
         ;;
     gui )
         echo "Starting a GUI terminal ..."
@@ -97,19 +196,22 @@ case $INF_JOB_NAME in
             exit 1
         fi
 
+        INF_AGENT_MODULE="`amsmodule getactmod tigervnc 2>&1`"
+        export INF_AGENT_MODULE
+
         # generate password
-        touch "$INF_WORK_DIR/${INF_WHOLE_NAME}.vncpsw"
+        touch "${INF_WHOLE_NAME}.vncpsw"
         if [ $? -ne 0 ]; then
             echo "" >&2
-            echo " >>> ERROR: Unable to create VNC password file '$INF_WORK_DIR/${INF_WHOLE_NAME}.vncpsw'!" >&2
+            echo " >>> ERROR: Unable to create VNC password file '${INF_WHOLE_NAME}.vncpsw'!" >&2
             echo "" >&2
             exit 1
         fi
-        chmod 600 "$INF_WORK_DIR/${INF_WHOLE_NAME}.vncpsw"
-        uuidgen | vncpasswd -f > "$INF_WORK_DIR/${INF_WHOLE_NAME}.vncpsw"
+        chmod 600 "${INF_WHOLE_NAME}.vncpsw"
+        uuidgen | vncpasswd -f > "${INF_WHOLE_NAME}.vncpsw"
 
         # start VNC server
-        vncserver -fg -rfbauth "$INF_WORK_DIR/${INF_WHOLE_NAME}.vncpsw" &> "$INF_WORK_DIR/${INF_WHOLE_NAME}.vnclog" &
+        vncserver -fg -rfbauth "$INF_WORK_DIR/${INF_WHOLE_NAME}.vncpsw" &> "${INF_WHOLE_NAME}.vncid" &
 
         VNCSERVER_PID=$!
 
@@ -119,17 +221,41 @@ case $INF_JOB_NAME in
         # setup terminal
         sleep 10  # wait for terminal initialization
 
-        INF_VNC_ID="`grep \"^VNCID:\" \"$INF_WORK_DIR/${INF_WHOLE_NAME}.vnclog\" | awk '{printf("%s",$2); }'`"
-
+        INF_VNC_ID="`grep \"^VNCID:\" \"${INF_WHOLE_NAME}.vncid\" | awk '{printf("%s",$2); }'`"
         if [ -z "$INF_VNC_ID" ]; then
             echo "" >&2
-            echo " >>> ERROR: Unable to get VNC ID from the log file '$INF_WORK_DIR/${INF_WHOLE_NAME}.vnclog'!" >&2
+            echo " >>> ERROR: Unable to get VNC ID from the vncid file '${INF_WHOLE_NAME}.vncid'!" >&2
             kill $VNCSERVER_PID
             echo "" >&2
             exit 1
         fi
-        echo "VNC ID: $INF_VNC_ID"
-        $ABS_ROOT/sbin/abs-update-infofile --vncid "$INF_VNC_ID" guiready
+        echo "VNC ID:      $INF_VNC_ID"
+
+        INF_VNC_DISPLAY="`grep \"^VNCDSP:\" \"${INF_WHOLE_NAME}.vncid\" | awk '{printf("%s",$2); }'`"
+        if [ -z "$INF_VNC_ID" ]; then
+            echo "" >&2
+            echo " >>> ERROR: Unable to get VNC DISPLAY from the vncid file '${INF_WHOLE_NAME}.vncid'!" >&2
+            kill $VNCSERVER_PID
+            echo "" >&2
+            exit 1
+        fi
+        echo "VNC DISPLAY: $INF_VNC_ID"
+
+        # create kill script
+        touch "${INF_WHOLE_NAME}.kill"
+        if [ $? -ne 0 ]; then
+            echo "" >&2
+            echo " >>> ERROR: Unable to create kill script '${INF_WHOLE_NAME}.kill'!" >&2
+            echo "" >&2
+            exit 1
+        fi
+        chmod 600 "${INF_WHOLE_NAME}.kill"
+        abs_write_kill_header   >  "${INF_WHOLE_NAME}.kill"
+        abs_write_kill_tigervnc >> "${INF_WHOLE_NAME}.kill"
+        abs_write_kill_footer   >> "${INF_WHOLE_NAME}.kill"
+
+        # update info file
+        $ABS_ROOT/sbin/abs-update-infofile --agent "$INF_AGENT_MODULE" --vncid "$INF_VNC_ID" guiready
 
         if [ $? -ne 0 ]; then
             echo "" >&2
@@ -173,10 +299,22 @@ case $INF_JOB_NAME in
         # this is used by pkill command to softly kill the job
         ./$INF_JOB_NAME &> ${INF_WHOLE_NAME}.stdout &
         MY_PID=$!
-        echo "$MY_PID" > ___JOB_IS_RUNNING___ # PID of the process
+
+        # create kill script
+        touch "${INF_WHOLE_NAME}.kill"
+        if [ $? -ne 0 ]; then
+            echo "" >&2
+            echo " >>> ERROR: Unable to create kill script '${INF_WHOLE_NAME}.kill'!" >&2
+            echo "" >&2
+            exit 1
+        fi
+        chmod 600 "${INF_WHOLE_NAME}.kill"
+        abs_write_kill_header >  "${INF_WHOLE_NAME}.kill"
+        abs_write_kill_script >> "${INF_WHOLE_NAME}.kill"
+        abs_write_kill_footer >> "${INF_WHOLE_NAME}.kill"
+
         wait $MY_PID
         export INF_JOB_EXIT_CODE=$?
-        rm -f ___JOB_IS_RUNNING___
 
         echo " Finished at   : `date`"
         echo " Exit code     : $INF_JOB_EXIT_CODE"
@@ -184,4 +322,8 @@ case $INF_JOB_NAME in
         echo "========================= End of the script execution =========================="
         ;;
 esac
+
+# remove the kill script
+rm -f "${INF_WHOLE_NAME}.kill"
+
 
diff --git a/share/scripts/abs-go b/share/scripts/abs-go
--- a/share/scripts/abs-go
+++ b/share/scripts/abs-go
@@ -11,22 +11,51 @@
 # (c) 2001-2004, Petr Kulhanek, kulhanek@chemi.muni.cz
 # ==============================================================================
 
+# INF_GO_MAIN_NODE
+# INF_GO_INPUT_MACHINE
+# INF_GO_INPUT_DIR
+# INF_GO_JOB_NAME
+# INF_GO_JOB_KEY
+# INF_GO_AGENT_MODULE
+# INF_GO_VNC_ID
+# INF_GO_VNC_PSW
+# INF_GO_SITE_ID
+
 # this is inline script
 case "$INF_GO_JOB_NAME" in
-    cli )
-        if [ -n "$INF_GO_MAIN_NODE" ] && [ -n "$INF_GO_JOB_KEY" ]; then
-            ssh -t -X "$INF_GO_MAIN_NODE" "site activate \"$INF_GO_SITE_ID\"; amsmodule add screen; screen -d -r \"T$INF_GO_JOB_KEY\""
-            echo ""
+    cli )   
+        if [ -n "$INF_GO_SITE_ID" ] && [ -n "$INF_GO_AGENT_MODULE" ] && \
+           [ -n "$INF_GO_MAIN_NODE" ] && [ -n "$INF_GO_JOB_KEY" ]; then
+            ssh -t -X "$INF_GO_MAIN_NODE" " \
+                site activate $INF_GO_SITE_ID; \
+                amsmodule add $INF_GO_AGENT_MODULE; \
+                if [ \$? -ne 0 ]; then \
+                    echo \"\" >&2; \
+                    echo \" >>> ERROR: Unable to activate CLI agent module '$INF_GO_AGENT_MODULE'!\" >&2; \
+                    echo \"\" >&2; \
+                    exit 1; \
+                fi; \
+                screen -d -r \"T$INF_GO_JOB_KEY\"; \
+                "
+            return $?
         fi
         return 0
         ;;
     gui )
-        amsmodule add tigervnc
-        vncviewer "$INF_GO_VNC_ID" -passwd "$INF_GO_VNC_PSW"
+        if [ -n "$INF_GO_AGENT_MODULE" ] && [ -n "$INF_GO_VNC_ID" ] && [ -n "$INF_GO_VNC_PSW" ] ; then
+            amsmodule add $INF_GO_AGENT_MODULE
+            if [ $? -ne 0 ]; then
+                echo "" >&2
+                echo " >>> ERROR: Unable to activate GUI agent module '$INF_GO_AGENT_MODULE'!" >&2
+                echo "" >&2
+                return 1
+            fi
+            vncviewer "$INF_GO_VNC_ID" -passwd "$INF_GO_VNC_PSW"
+            return $?
+        fi
         ;;
     * )
         # go to working directory
-
         if [ -n "$INF_GO_MAIN_NODE" ] && [ -n "$INF_GO_WORK_DIR" ] && [ -n "$INF_GO_SITE_ID" ] ; then
             ssh -t -X $INF_GO_MAIN_NODE \
                       INF_GO_SITE_ID="$INF_GO_SITE_ID" \
@@ -41,7 +70,7 @@ case "$INF_GO_JOB_NAME" in
         if [ -z "$INF_GO_MAIN_NODE" ] && [ -n "$INF_GO_INPUT_MACHINE" ] && [ -n "$INF_GO_INPUT_DIR" ]; then
             if [ "$INF_GO_INPUT_MACHINE" != "$HOSTNAME" ]; then
                 echo ""
-                echo " WARNING: The job input directory is located on a remote computer."
+                echo " WARNING: The job input directory is located on the remote computer."
                 echo "          Job input dir: $INF_GO_INPUT_MACHINE:$INF_GO_INPUT_DIR"
                 echo "          Hostname     : $HOSTNAME"
             fi
diff --git a/share/scripts/abs-kill b/share/scripts/abs-kill
--- a/share/scripts/abs-kill
+++ b/share/scripts/abs-kill
@@ -12,44 +12,34 @@
 # ==============================================================================
 #
 # required input
-# INF_KILL_JOB_NAME
-# INF_KILL_JOB_NAME_SUFFIX
-# INF_KILL_JOB_KEY
 # INF_KILL_MAIN_NODE
 # INF_KILL_WORK_DIR
+# INF_KILL_WHOLE_NAME
+# INF_KILL_JOB_KEY
 
-# soft kill mode - do we have all data?
+# soft kill mode - call kill script in the working directory ...
 
-case "$INF_KILL_JOB_NAME" in
-    cli )
-        if [ -n "$INF_KILL_MAIN_NODE" ] && [ -n "$INF_KILL_JOB_KEY" ]; then
-            echo ""
-            echo "Terminating the job CLI terminal ..."
-            ssh -x -t "$INF_KILL_MAIN_NODE" screen -d -r "T$INF_KILL_JOB_KEY -X quit"
-            echo ""
+if [ -n "$INF_KILL_MAIN_NODE" ] && [ -n "$INF_KILL_JOB_KEY" ] && \
+   [ -n "$INF_KILL_WORK_DIR" ] && [ -n "$INF_KILL_WHOLE_NAME" ]; then
+   echo "Calling the kill script $INF_KILL_MAIN_NODE:$INF_KILL_WORK_DIR/$INF_KILL_WHOLE_NAME.kill $INF_KILL_JOB_KEY ..."
+   ssh -x $INF_KILL_MAIN_NODE " \
+        cd \"$INF_KILL_WORK_DIR\"; \
+        if [ \$? -ne 0 ]; then \
+            echo \"\" >&2; \
+            echo \" >>> ERROR: Unable to set the working directory '$INF_KILL_WORK_DIR'!\" >&2; \
+            echo \"\" >&2; \
+            exit 1; \
+        fi; \
+        if ! [ -f \"${INF_KILL_WHOLE_NAME}.kill\" ]; then \
+            echo \"\" >&2; \
+            echo \" >>> ERROR: Unable to find the kill script '${INF_KILL_WHOLE_NAME}.kill'!\" >&2; \
+            echo \"\" >&2; \
+            exit 1; \
         fi
-        ;;
-    gui )
-        # not implemented
-        ;;
-    * )
-        if [ -z "$INF_KILL_MAIN_NODE" ] || [ -z "$INF_KILL_WORK_DIR" ]; then
-            exit 0
-        fi
+        bash \"${INF_KILL_WHOLE_NAME}.kill\" \"$INF_KILL_JOB_KEY\"; \
+        "
+    exit $?
+fi
 
-        # send TERM signal to user script
-        echo ""
-        echo "Sending TERM signal to "$INF_KILL_MAIN_NODE:$INF_KILL_WORK_DIR" ..."
-        ssh -x $INF_KILL_MAIN_NODE "cd $INF_KILL_WORK_DIR; \
-                if ! [ -f ___JOB_IS_RUNNING___ ]; then \
-                   echo \"\"; \
-                   echo \"ERROR: The user script has not been started or it has been terminated already!\"; \
-                   echo \"\"; exit 1; \
-                fi; \
-                echo \">>> Process ID: \`cat ___JOB_IS_RUNNING___\`\"; \
-                echo \">>> TERMINATED ON USER REQUEST \`date\`\" >> \"${INF_KILL_JOB_NAME}${INF_KILL_JOB_NAME_SUFFIX}.stdout\"; \
-                kill -TERM \`cat ___JOB_IS_RUNNING___\`; \
-                exit 0;"
-        echo ""
-        ;;
-esac
+# not supported
+exit 1
