submit

diff --git a/share/scripts/abs-execution-script-L0 b/share/scripts/abs-execution-script-L0
--- a/share/scripts/abs-execution-script-L0
+++ b/share/scripts/abs-execution-script-L0
@@ -1,6 +1,7 @@
 #!/bin/bash
 # ==============================================================================
 # ABS
+# (c) 2017, Petr Kulhanek, kulhanek@chemi.muni.cz
 # (c) 2012, Petr Kulhanek, kulhanek@chemi.muni.cz
 # (c) 2008-2009, Petr Kulhanek, kulhanek@chemi.muni.cz
 # Charon Extension Layer v0.9
@@ -23,7 +24,7 @@ echo
 echo "################################################################################"
 echo "#                          *** INFINITY JOB ***                                #"
 echo "#                                                                              #"
-echo "###                    Beggining of script execution                        ####"
+echo "###                  Beggining of the script execution                      ####"
 echo "#                                                                              #"
 echo "# # Date: `printf %-67s \"$_DATE\"`# #"
 echo "#                                                                              #"
@@ -33,32 +34,39 @@ echo " Initial job information (recovered from transmitted environment):"
 echo "--------------------------------------------------------------------------------"
 echo " Job name             : $INF_JOB_NAME"
 echo " Job name suffix      : $INF_JOB_NAME_SUFFIX"
-echo " Job input machine    : $INF_JOB_MACHINE"
-echo " Job input path       : $INF_JOB_PATH"
+echo " Job input machine    : $INF_INPUT_MACHINE"
+echo " Job input dir        : $INF_INPUT_DIR"
 echo " Job storage machine  : $INF_STORAGE_MACHINE"
-echo " Job storage path     : $INF_STORAGE_PATH"
+echo " Job storage path     : $INF_STORAGE_DIR"
 echo " Data IN copy mode    : $INF_DATAIN"
 echo " Data OUT copy mode   : $INF_DATAOUT"
 echo " Job key              : $INF_JOB_KEY"
 echo "------------------------------------------------------"
 echo " Hostname             : `hostname -f`"
+echo " AMS boot script      : $INF_BOOT_SCRIPT"
 echo " Site support         : $AMS_SITE_SUPPORT"
 echo " Site ID              : $INF_SITE_ID"
 echo " ABS module version   : $INF_ABS_VERSION"
 echo " ABS Root             : $ABS_ROOT"
-echo " AMS boot script      : $INF_BOOT_SCRIPT"
+echo "------------------------------------------------------"
+export INF_SSH_OPTIONS="StrictHostKeyChecking=no"
+echo " SSH Options          : $INF_SSH_OPTIONS"
 echo ""
+
+# backward compatibility setup
+export INF_JOB_MACHINE=$INF_INPUT_MACHINE
+export INF_JOB_PATH=$INF_INPUT_PATH
 
 echo ""
 echo "#-------------------------------------------------------------------------------"
-echo "# L0 First execution layer ..."
+echo "# L0 Booting execution layer ..."
 echo "#-------------------------------------------------------------------------------"
-
-# boot AMS ---------------------------------------------------------------------
 echo "User identity ..."
 echo "UID   : `id`"
 echo "Umask : `umask`"
 echo
+
+# boot AMS ---------------------------------------------------------------------
 
 if [ -f "$INF_BOOT_SCRIPT" ]; then
     # boot AMS system
@@ -67,17 +75,17 @@ fi
 
 echo "$ site -v activate $INF_SITE_ID"
 
-site -v activate $INF_SITE_ID
+site -v activate "$INF_SITE_ID"
 
 if [ $? -ne 0 ]; then
     echo "" >&2
-    echo " ERROR: Unable to activate site ($INF_SITE_ID)!" >&2
-    echo "        Please send contents of this file to the site support: $AMS_SITE_SUPPORT" >&2
+    echo " ERROR: Unable to activate the site ($INF_SITE_ID)!" >&2
+    echo "        Please send contents of this output to the site support: $AMS_SITE_SUPPORT" >&2
     echo "" >&2
     exit 1
 fi
 
-# destroy ams host cache
+# do not use the host chache as it can be outdated
 echo "$ ams-host --nocache"
 
 ams-host --nocache
@@ -89,40 +97,34 @@ amsmodule --system add abs:$INF_ABS_VERSION
 
 if [ $? -ne 0 ]; then
     echo "" >&2
-    echo " ERROR: Unable to add 'abs:$INF_MODULE_VERS' module!" >&2
-    echo "        Please send contents of this file to the site support: $AMS_SITE_SUPPORT" >&2
-
+    echo " ERROR: Unable to add the 'abs:$INF_MODULE_VERS' module!" >&2
+    echo "        Please send contents of this output to the site support: $AMS_SITE_SUPPORT" >&2
     echo "" >&2
     exit 1
 fi
 
-# =============================================================================
-# Stage 01 - execute wrapper script +++++++++++++++++++++++++++++++++++++++++++
-# =============================================================================
+# ==============================================================================
+
+# load ABS library
+source $ABS_ROOT/share/scripts/abs-execution-script-LL
 
 # Restore job environment ...
 source $ABS_ROOT/share/scripts/abs-execution-script-L1
-if [ $? -ne 0 ]; then exit 1; fi
 
 # Prepare working directory ...
 source $ABS_ROOT/share/scripts/abs-execution-script-L2
-if [ $? -ne 0 ]; then exit 1; fi
 
 # Copy input job data ...
-$ABS_ROOT/share/scripts/abs-execution-script-L3
-if [ $? -ne 0 ]; then exit 1; fi
+$ABS_ROOT/share/scripts/abs-execution-script-L3 || exit 1
 
 # Start job ...
 source $ABS_ROOT/share/scripts/abs-execution-script-L4
-if [ $? -ne 0 ]; then exit 1; fi
 
 # Sync data ...
-$ABS_ROOT/share/scripts/abs-execution-script-L5
-if [ $? -ne 0 ]; then exit 1; fi
+$ABS_ROOT/share/scripts/abs-execution-script-L5 || exit 1
 
 # Clean ...
-$ABS_ROOT/share/scripts/abs-execution-script-L6
-if [ $? -ne 0 ]; then exit 1; fi
+$ABS_ROOT/share/scripts/abs-execution-script-L6 || exit 1
 
 # =============================================================================
 
@@ -131,7 +133,7 @@ echo "##########################################################################
 echo "#                                                                              #"
 echo "# # Date: `printf %-67s \"$_DATE\"`# #"
 echo "#                                                                              #"
-echo "###                        End of script execution                          ####"
+echo "###                      End of the script execution                        ####"
 echo "#                                                                              #"
 echo "################################################################################"
 echo
diff --git a/share/scripts/abs-execution-script-L2 b/share/scripts/abs-execution-script-L2
--- a/share/scripts/abs-execution-script-L2
+++ b/share/scripts/abs-execution-script-L2
@@ -1,6 +1,7 @@
 #!/bin/bash
 # =============================================================================
 # ABS
+# (c) 2017, Petr Kulhanek, kulhanek@chemi.muni.cz
 # (c) 2012, Petr Kulhanek, kulhanek@chemi.muni.cz
 # (c) 2008-2009, Petr Kulhanek, kulhanek@chemi.muni.cz
 # Charon Extension Layer v0.9
@@ -19,20 +20,17 @@ echo "# L2.1: Resources files ..."
 echo "# ------------------------------------------------------------------------------"
 echo
 
-
-# we need PBS_NODEFILE if it does not exist we create placebo with hostname
+echo ""
+echo "# PBS_NODEFILE ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
+echo "# File: $PBS_NODEFILE"
 
 if ! [ -f "$PBS_NODEFILE" ]; then
     echo ""  >&2
     echo " ERROR: PBS_NODEFILE does not exist!"  >&2
-    echo "        File path : '$PBS_NODEFILE'"  >&2
     echo "" >&2
     exit 1
 fi
 
-echo ""
-echo "# PBS_NODEFILE ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
-echo "# File: $PBS_NODEFILE"
 cat "$PBS_NODEFILE"
 
 # ------------------------------------------------------------------------------
@@ -70,44 +68,42 @@ fi
 
 echo ""
 echo "# ------------------------------------------------------------------------------"
-echo "# L2.2: Prepare working directory ..."
+echo "# L2.2: Prepare the working directory ..."
 echo "# ------------------------------------------------------------------------------"
-echo " Data IN copy mode  : $INF_DATAIN"
 export INF_MAIN_NODE=`hostname -f`
-echo " Main node          : $INF_MAIN_NODE"
 echo " Job ID             : $INF_JOB_ID"
-echo " Scratch type       : $INF_SCRATCH_TYPE"
+echo " Main working node  : $INF_MAIN_NODE"
+echo " Working dir type   : $INF_WORK_DIR_TYPE"
+echo " Data IN copy mode  : $INF_DATAIN"
 
 # ------------------------------------------------------------------------------
 # set working directory
 
 INF_WORK_DIR="`$ABS_ROOT/sbin/abs-get-work-dir --type main $INF_WORK_DIR_TYPE`"
-echo " Scratch dir        : $INF_WORK_DIR"
 if [ $? -ne -0 ]; then
     return 1
 fi
-INF_WORK_DIR="`eval echo "$INF_WORK_DIR"`"
-
 echo " Working directory  : $INF_WORK_DIR"
-echo ""
+INF_WORK_DIR="`eval echo "$INF_WORK_DIR"`"
+echo " Working directory  : $INF_WORK_DIR"
 
 # ------------------------------------------------------------------------------
 # create working directories if necessary
-
+echo ""
 case $INF_DATAIN in
     keep)
         echo ">>> $INF_MAIN_NODE:$INF_WORK_DIR ---"
         timeout 30 df -h
         if [ $? -ne 0 ]; then
-            echo ">>> WARNING: df command was not completed due to error or timeout."
+            echo ">>> WARNING: the df command was not completed due to an error or timeout."
         fi
     ;;
     copy)
-        echo " Create working directories on nodes:"
+        echo " Create the working directories on nodes:"
         for NODE_NAME in `cat $PBS_NODEFILE | sort -u`; do
             echo ""
             echo ">>> $NODE_NAME:$INF_WORK_DIR ---"
-            ssh -x -o "StrictHostKeyChecking=no" $NODE_NAME "timeout 30 df -h; if [ \$? -ne 0 ]; then echo \">>> WARNING: df command was not completed due to error or timeout.\"; fi; mkdir -p $INF_WORK_DIR"
+            ssh -x -o "$INF_SSH_OPTIONS" $NODE_NAME "timeout 30 df -h; if [ \$? -ne 0 ]; then echo \">>> WARNING: the df command was not completed due to an error or timeout.\"; fi; mkdir -p $INF_WORK_DIR"
 
             if [ $? -ne 0 ]; then
                 echo "" >&2
@@ -124,8 +120,8 @@ export INF_WORK_DIR
 # ------------------------------------------------------------------------------
 # go to working directory
 echo ""
-echo " Changing current directory to working directory ..."
-cd $INF_WORK_DIR
+echo " Changing the current directory to the working directory ..."
+cd "$INF_WORK_DIR"
 
 if [ $? -ne 0 ]; then
     echo "" >&2
@@ -133,7 +129,6 @@ if [ $? -ne 0 ]; then
     echo "" >&2
     exit 1
 fi
-echo " Success."
 
 # ------------------------------------------------------------------------------
 # create sorted node file
@@ -145,7 +140,7 @@ export AMS_NODEFILE
 $ABS_ROOT/sbin/abs-sort-nodes $PBS_NODEFILE $INF_MAIN_NODE > $INF_NODEFILE
 if [ $? -ne 0 ]; then
     echo "" >&2
-    echo " ERROR: Unable to sort computational nodes!" >&2
+    echo " ERROR: Unable to sort the computational nodes!" >&2
     echo "" >&2
     return 1
 fi
@@ -169,7 +164,6 @@ fi
 # move info file to working directory
 
 mv "$TMPDIR/${_TNAME_}.info" "$INF_WORK_DIR/${INF_WHOLE_NAME}.info"
-
 if [ $? -ne 0 ]; then
     echo "" >&2
     echo " ERROR: Unable to move the job info file into the working directory!" >&2
@@ -181,10 +175,9 @@ fi
 # update info file
 
 echo ""
-echo " Write job start info ..."
+echo " Write the job start info ..."
 
 $ABS_ROOT/sbin/abs-update-infofile start
-
 if [ $? -ne 0 ]; then
     echo "" >&2
     echo " ERROR: Unable to update job status in the job info file!" >&2
@@ -192,22 +185,16 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
+echo " Update the info file in the input directory ..."
 case $INF_DATAIN in
+    keep)
+        echo " > already updated in the keep datain mode ..."
+    ;;
     copy)
-    if [ "$INF_REMOTE_JOBDIR" == "NO" ]; then
-        cp "$INF_WORK_DIR/${INF_WHOLE_NAME}.info" "$INF_JOB_PATH/${INF_WHOLE_NAME}.info"
-    else
-        /usr/bin/scp -o "StrictHostKeyChecking=no" \
-            "$INF_WORK_DIR/${INF_WHOLE_NAME}.info" "$INF_STORAGE_MACHINE:$INF_STORAGE_PATH/${INF_WHOLE_NAME}.info"
-    fi
-    echo "" >&2
-    echo " ERROR: Unable to update info file in the job input directory!" >&2
-    echo "" >&2
-    exit 1
+        inf-retry-cmd inf-copy-to-inputdir "$INF_WORK_DIR/${INF_WHOLE_NAME}.info" "${INF_WHOLE_NAME}.info"
+        if [ $? -ne 0 ]; then exit 1; fi
+    ;;
 esac
-
-echo " Date = `date`"
-echo " Success."
 
 echo ""
 echo "# ------------------------------------------------------------------------------"
@@ -230,7 +217,7 @@ type numactl &> /dev/null
 if [ $? -eq 0 ]; then
     numactl --show
 else
-    echo ">>> INFO: numactl command not available ... skipping"
+    echo ">>> INFO: the numactl command not available ... skipping"
 fi
 
 # ------------------------------------------------------------------------------
diff --git a/share/scripts/abs-execution-script-L5 b/share/scripts/abs-execution-script-L5
--- a/share/scripts/abs-execution-script-L5
+++ b/share/scripts/abs-execution-script-L5
@@ -1,6 +1,7 @@
 #!/bin/bash
 # =============================================================================
 # ABS
+# (c) 2017, Petr Kulhanek, kulhanek@chemi.muni.cz
 # (c) 2008-2009, Petr Kulhanek, kulhanek@chemi.muni.cz
 # Charon Extension Layer v0.9
 # (c) 2006, Petr Kulhanek, kulhanek@chemi.muni.cz
@@ -14,100 +15,47 @@ echo ""
 echo "# ------------------------------------------------------------------------------"
 echo "# L5.1: Data in the working directory ..."
 echo "# ------------------------------------------------------------------------------"
-echo "User identity ..."
-echo "UID   : `id`"
-echo "Umask : `umask`"
 echo
 
 ls -l
 
 echo ""
 echo "# ------------------------------------------------------------------------------"
-echo "# L5.2: Syncing data [$INF_SYNC_MODE] ..."
+echo "# L5.2: Copy the working directory to the input directory ..."
 echo "# ------------------------------------------------------------------------------"
-
-# do not copy info file
-echo "${INF_WHOLE_NAME}.info" > $TMPDIR/${_TNAME_}.excluded
-
-echo " Final exclusion list:"
-cat $TMPDIR/${_TNAME_}.excluded | awk '{ printf("   %s\n",$0); }'
-echo ""
+echo " Data OUT copy mode : $INF_DATAOUT"
 
 # setup rsync options
 if [ "$INF_FS_TYPE" == "inconsistent" ]; then
     RSYNC_OPTS="--no-g"
 fi
 
-case $INF_SYNC_MODE in
-    sync )
-        echo " Data from the main node are only copied ..."
-
-        if [ "$INF_REMOTE_JOBDIR" == "YES" ]; then
-            echo " Copy mode     : remote rsync"
-            echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
-            rsync -av $RSYNC_OPTS -e "ssh -x -o \"StrictHostKeyChecking=no\"" --exclude-from="$TMPDIR/${_TNAME_}.excluded" \
-                  "$INF_WORK_DIR/" "$INF_JOB_MACHINE:$INF_JOB_PATH/$INF_OUTPUT_SUFFIX/"
-
-            if [ $? -ne 0 ]; then
-                echo "" >&2
-                echo " ERROR: Unable to copy the job data from the main computational" >&2
-                echo "        node to the input job directory!" >&2
-                echo "" >&2
-                exit 1
-            fi
-            echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
-        else
-            echo " Copy mode     : local rsync"
-            echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
-            rsync -av $RSYNC_OPTS --exclude-from="$TMPDIR/${_TNAME_}.excluded" "$INF_WORK_DIR/" \
-                  "$INF_JOB_PATH/$INF_OUTPUT_SUFFIX/"
-
-            if [ $? -ne 0 ]; then
-                echo "" >&2
-                echo " ERROR: Unable to copy the job data from the main computational" >&2
-                echo "        node to the input job directory!" >&2
-                echo "" >&2
-                exit 1
-            fi
-            echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
-        fi
+case $INF_DATAOUT in
+    keep )
+        echo " Data left in the working directory, which is presumably the input directory ..."
     ;;
-    jobdir )
-        echo " The job will was executed in the input job directory, no data are copied back ..."
+    copy)
+        echo " Data from the main working node are only copied ..."
+        inf-retry-cmd inf-rsync-from-inputdir
+        if [ $? -ne 0 ]; then exit 1; fi
     ;;
 esac
-
-rm -f $TMPDIR/${_TNAME_}.excluded
-
-echo " Success."
 
 # -----------------------------------------------------------------------------
 
 echo ""
-echo " Write job end info ..."
+echo " Write the job end info and update the info file ..."
 
 $ABS_ROOT/sbin/abs-update-infofile stop
-
 if [ $? -ne 0 ]; then
     echo "" >&2
-    echo " ERROR: Unable to update job status in the job info file!" >&2
+    echo " ERROR: Unable to update the job status in the job info file!" >&2
     echo "" >&2
     exit 1
 fi
 
-if [ "$INF_REMOTE_JOBDIR" == "NO" ]; then
-    echo " Local update ..."
-    if [ "$INF_SYNC_MODE" != "jobdir" ]; then
-        cp "$INF_WORK_DIR/${INF_WHOLE_NAME}.info" "$INF_JOB_PATH/${INF_WHOLE_NAME}.info"
-    fi
-else
-    echo " Remote update ..."
-    /usr/bin/scp -o "StrictHostKeyChecking=no" \
-        "$INF_WORK_DIR/${INF_WHOLE_NAME}.info" "$INF_JOB_MACHINE:$INF_JOB_PATH/${INF_WHOLE_NAME}.info"
-fi
-
-echo " Date = `date`"
-echo " Success."
+inf-retry-cmd inf-copy-to-inputdir "$INF_WORK_DIR/${INF_WHOLE_NAME}.info" "${INF_WHOLE_NAME}.info"
+if [ $? -ne 0 ]; then exit 1; fi
 
 # notify user about the job end
 case $INF_JOB_NAME in
@@ -123,10 +71,6 @@ case $INF_JOB_NAME in
         fi
         ;;
 esac
-
-# write simple statistics into stat database -----------------------------------
-
-# FIXME
 
 # ------------------------------------------------------------------------------
 
