update

diff --git a/share/scripts/abs-go-remote b/share/scripts/abs-go-remote
--- a/share/scripts/abs-go-remote
+++ b/share/scripts/abs-go-remote
@@ -12,22 +12,20 @@
 # (c) 2001-2004, Petr Kulhanek, kulhanek@chemi.muni.cz
 # ==============================================================================
 
-INF_AMS_SITE=$INF_GO_SITE
 INF_WORK_DIR=$INF_GO_WORK_DIR
 INF_AMS_SITE_EMODS=$INF_GO_EXPORTED_MODULES_1
 INF_JOB_EMODS=$INF_GO_EXPORTED_MODULES_2
 
 # activate bash profile
-# if [ -f /etc/profile ]; then . /etc/profile; fi
 if [ -f ~/.bash_profile ]; then . ~/.bash_profile; fi
 
 if [ -z "$AMS_ROOT" ]; then
     source "$INF_GO_BOOT_SCRIPT"
 fi
 
-site activate $INF_AMS_SITE 2> /dev/null
+site --job init
 if [ $? -ne 0 ]; then
-    echo " >>> ERROR: The site ($INF_AMS_SITE) cannot be activated!" >&2
+    echo " >>> ERROR: The site ($INF_GO_SITE) cannot be activated!" >&2
     echo >&2
     exit 1
 fi
