data management

diff --git a/share/scripts/abs-sync b/share/scripts/abs-sync
--- a/share/scripts/abs-sync
+++ b/share/scripts/abs-sync
@@ -16,6 +16,8 @@
 # INF_SYNC_WORK_DIR
 # INF_SYNC_INPUT_DIR
 # INF_SYNC_INPUT_MACHINE
+# INF_WI_RSYNCOPTS
+# INF_SSH_OPTIONS
 
 #===============================================================================
 #-------------------------------------------------------------------------------
@@ -23,7 +25,7 @@
 
 echo "List of files in working directory:"
 echo "========================================================"
-ssh -x $INF_SYNC_MAIN_NODE "cd $INF_SYNC_WORK_DIR; if [ \$? -ne 0 ]; then echo; exit 1; fi; \ls -l *"
+ssh -x $INF_SSH_OPTIONS $INF_SYNC_MAIN_NODE "cd $INF_SYNC_WORK_DIR; if [ \$? -ne 0 ]; then echo; exit 1; fi; \ls -l *"
 
 if [ $? -ne 0 ]; then
     exit 1
@@ -32,24 +34,13 @@ fi
 echo ""
 if [ "$INF_SYNC_ALL" == "YES" ]; then
     echo -n "All files will be synchronized by rsync "
-    if [ "$HOSTNAME" == "$INF_SYNC_MAIN_NODE" ]; then
-        echo "from job working directory ..."
-        rsync -av --exclude "___JOB_IS_RUNNING___" "$INF_SYNC_WORK_DIR/" "$INF_SYNC_INPUT_MACHINE:$INF_SYNC_INPUT_DIR/" 2>&1 | awk '{ printf("   %s\n",$0); }'
-        if [ $? -ne 0 ]; then
-            echo ""
-            echo " ERROR: Unable to copy all files!"
-            echo ""
-            exit 1
-        fi
-    else
-        echo "from job input directory ..."
-        rsync -av --exclude "___JOB_IS_RUNNING___" "$INF_SYNC_MAIN_NODE:$INF_SYNC_WORK_DIR/" "$INF_SYNC_INPUT_DIR/" 2>&1 | awk '{ printf("   %s\n",$0); }'
-        if [ $? -ne 0 ]; then
-            echo ""
-            echo " ERROR: Unable to copy all files!"
-            echo ""
-            exit 1
-        fi
+    rsync -av $INF_WI_RSYNCOPTS -e "ssh -x $INF_SSH_OPTIONS" --exclude "___JOB_IS_RUNNING___" \
+          "$INF_SYNC_MAIN_NODE:$INF_SYNC_WORK_DIR/" "$INF_SYNC_INPUT_MACHINE:$INF_SYNC_INPUT_DIR/" 2>&1 | awk '{ printf("   %s\n",$0); }'
+    if [ $? -ne 0 ]; then
+        echo ""
+        echo " ERROR: Unable to copy all files!"
+        echo ""
+        exit 1
     fi
     echo "Done."
     echo ""
@@ -92,7 +83,8 @@ for SFILE in $FILES; do
     if [ "$SFILE" == "___JOB_IS_RUNNING___" ]; then
         echo "Skipped."
     else
-        /usr/bin/scp -r $INF_SYNC_MAIN_NODE:$INF_SYNC_WORK_DIR/$SFILE $INF_SYNC_INPUT_MACHINE:$INF_SYNC_INPUT_DIR > /dev/null
+        rsync -av $INF_WI_RSYNCOPTS -e "ssh -x $INF_SSH_OPTIONS" \
+              $INF_SYNC_MAIN_NODE:$INF_SYNC_WORK_DIR/$SFILE $INF_SYNC_INPUT_MACHINE:$INF_SYNC_INPUT_DIR > /dev/null
         if [ $? -ne 0 ]; then
             echo ""
             echo " ERROR: Unable to copy the file!"
