pgo, psync, pkill improvemetns

diff --git a/share/scripts/abs-sync b/share/scripts/abs-sync
--- a/share/scripts/abs-sync
+++ b/share/scripts/abs-sync
@@ -46,6 +46,19 @@ if ! [ -e "$ABS_RSYNC" ]; then
     exit 1
 fi
 
+# test if PWD is input job dir
+if [ "$HOSTNAME" != "$INF_SYNC_MAIN_NODE" ]; then
+    grep "$INF_JOB_KEY" "$PWD/${INF_SYNC_WHOLE_NAME}.infkey" &> /dev/null
+    if [ $? -ne 0 ]; then
+        echo "" >&2
+        echo " >>> ERROR: The current directory is not the same as the job input dorectory (job keys does not match)!" >&2
+        echo "            Input dir:   $INF_SYNC_INPUT_DIR" >&2
+        echo "            Current dir: $PWD" >&2
+        echo "" >&2
+        exit 1
+    fi
+fi
+
 echo "List of files in the working directory:"
 echo "========================================================"
 ssh -x $INF_SSH_OPTIONS $INF_SYNC_MAIN_NODE "cd $INF_SYNC_WORK_DIR; if [ \$? -ne 0 ]; then echo; exit 1; fi; \ls -l *"
