changes in infex scripts - excluded files and reporting FS after job end

diff --git a/share/scripts/abs-execution-script-L5 b/share/scripts/abs-execution-script-L5
--- a/share/scripts/abs-execution-script-L5
+++ b/share/scripts/abs-execution-script-L5
@@ -13,11 +13,47 @@
 
 echo ""
 echo "# ------------------------------------------------------------------------------"
-echo "# L5.1: Data in the working directory ..."
+echo "# L5.1a: Data in the working directory ..."
 echo "# ------------------------------------------------------------------------------"
 echo
 
-ls -la
+case $INF_DATAOUT in
+    copy)
+        for NODE_NAME in `cat $PBS_NODEFILE | sort -u`; do
+            echo ""
+            echo ">>> $NODE_NAME:$INF_WORK_DIR -----------------------"
+            ssh -x "$INF_SSH_OPTIONS" $NODE_NAME "cd $INF_WORK_DIR; ls -la"
+        done
+        ;;
+    keep)
+        echo ""
+        echo ">>> $INF_MAIN_NODE:$INF_WORK_DIR -------------------"
+        ls -la
+        ;;
+esac
+
+echo ""
+echo "# ------------------------------------------------------------------------------"
+echo "# L5.1b: Status of filesystems  ..."
+echo "# ------------------------------------------------------------------------------"
+
+case $INF_DATAOUT in
+    copy)
+        for NODE_NAME in `cat $PBS_NODEFILE | sort -u`; do
+            echo ""
+            echo ">>> $NODE_NAME -------------------------------------"
+            ssh -x "$INF_SSH_OPTIONS" $NODE_NAME "timeout 30 df -h; if [ \$? -ne 0 ]; then echo \">>> WARNING: the df command was not completed due to an error or timeout.\"; fi;"
+        done
+        ;;
+    keep)
+        echo ""
+        echo ">>> $INF_MAIN_NODE ---------------------------------"
+        timeout 30 df -h
+        if [ $? -ne 0 ]; then
+            echo ">>> WARNING: the df command was not completed due to an error or timeout."
+        fi
+        ;;
+esac
 
 echo ""
 echo "# ------------------------------------------------------------------------------"
