data management

diff --git a/share/scripts/abs-sync b/share/scripts/abs-sync
--- a/share/scripts/abs-sync
+++ b/share/scripts/abs-sync
@@ -34,13 +34,26 @@ fi
 echo ""
 if [ "$INF_SYNC_ALL" == "YES" ]; then
     echo -n "All files will be synchronized by rsync "
-    rsync -av $INF_WI_RSYNCOPTS -e "ssh -x $INF_SSH_OPTIONS" --exclude "___JOB_IS_RUNNING___" \
-          "$INF_SYNC_MAIN_NODE:$INF_SYNC_WORK_DIR/" "$INF_SYNC_INPUT_MACHINE:$INF_SYNC_INPUT_DIR/" 2>&1 | awk '{ printf("   %s\n",$0); }'
-    if [ $? -ne 0 ]; then
-        echo ""
-        echo " ERROR: Unable to copy all files!"
-        echo ""
-        exit 1
+    if [ "$HOSTNAME" == "$INF_SYNC_MAIN_NODE" ]; then
+        echo "from the working directory ..."
+        rsync -av $INF_WI_RSYNCOPTS -e "ssh -x $INF_SSH_OPTIONS" --exclude "___JOB_IS_RUNNING___" \
+              "$INF_SYNC_WORK_DIR/" "$INF_SYNC_INPUT_MACHINE:$INF_SYNC_INPUT_DIR/" 2>&1 | awk '{ printf("   %s\n",$0); }'
+        if [ $? -ne 0 ]; then
+            echo ""
+            echo " ERROR: Unable to copy all files!"
+            echo ""
+            exit 1
+        fi
+    else
+        echo "from the input directory ..."
+        rsync -av $INF_WI_RSYNCOPTS -e "ssh -x $INF_SSH_OPTIONS" --exclude "___JOB_IS_RUNNING___" \
+              "$INF_SYNC_MAIN_NODE:$INF_SYNC_WORK_DIR/" "$INF_SYNC_INPUT_DIR/" 2>&1 | awk '{ printf("   %s\n",$0); }'
+        if [ $? -ne 0 ]; then
+            echo ""
+            echo " ERROR: Unable to copy all files!"
+            echo ""
+            exit 1
+        fi
     fi
     echo "Done."
     echo ""
@@ -79,17 +92,28 @@ fi
 echo ""
 
 for SFILE in $FILES; do
-    echo -n "Copying file '$SFILE' by scp ... "
+    echo -n "Copying file '$SFILE' by rsync ... "
     if [ "$SFILE" == "___JOB_IS_RUNNING___" ]; then
         echo "Skipped."
     else
-        rsync -av $INF_WI_RSYNCOPTS -e "ssh -x $INF_SSH_OPTIONS" \
-              $INF_SYNC_MAIN_NODE:$INF_SYNC_WORK_DIR/$SFILE $INF_SYNC_INPUT_MACHINE:$INF_SYNC_INPUT_DIR > /dev/null
-        if [ $? -ne 0 ]; then
-            echo ""
-            echo " ERROR: Unable to copy the file!"
-            echo ""
-            exit 1
+        if [ "$HOSTNAME" == "$INF_SYNC_MAIN_NODE" ]; then
+            rsync -av $INF_WI_RSYNCOPTS -e "ssh -x $INF_SSH_OPTIONS" \
+                  "$INF_SYNC_WORK_DIR/$SFILE" "$INF_SYNC_INPUT_MACHINE:$INF_SYNC_INPUT_DIR/" > /dev/null
+            if [ $? -ne 0 ]; then
+                echo ""
+                echo " ERROR: Unable to copy the file!"
+                echo ""
+                exit 1
+            fi
+        else
+            rsync -av $INF_WI_RSYNCOPTS -e "ssh -x $INF_SSH_OPTIONS" \
+                  "$INF_SYNC_MAIN_NODE:$INF_SYNC_WORK_DIR/$SFILE" "$INF_SYNC_INPUT_DIR/" > /dev/null
+            if [ $? -ne 0 ]; then
+                echo ""
+                echo " ERROR: Unable to copy the file!"
+                echo ""
+                exit 1
+            fi
         fi
         echo "Done."
     fi
