update

diff --git a/share/scripts/abs-execution-script-L0 b/share/scripts/abs-execution-script-L0
--- a/share/scripts/abs-execution-script-L0
+++ b/share/scripts/abs-execution-script-L0
@@ -110,11 +110,19 @@ AMS_HOST_CACHE="/tmp/ams_cache.${USER}.${PBS_JOBID}"
 export AMS_HOST_CACHE
 
 # boot AMS if not already done
-if [ -z "$AMS_ROOT" ]; then
+if [ -z "$AMS_ROOT_V9" ]; then
     if [ -f "$INF_BOOT_SCRIPT" ]; then
         # boot AMS system
         source $INF_BOOT_SCRIPT
     fi
+fi
+
+if [ -z "$AMS_ROOT_V9" ]; then
+    echo "" >&2
+    echo " >>> ERROR: Advanced Module System (AMS) is not available!" >&2
+    echo "            Please send contents of this output to the site support: $AMS_SITE_SUPPORT" >&2
+    echo "" >&2
+    exit 1
 fi
 
 # do not use the host chache as it can be outdated
@@ -134,7 +142,6 @@ if [ $? -ne 0 ]; then
     echo " >>> ERROR: Unable to add the 'abs:$INF_ABS_VERSION' module!" >&2
     echo "            Please send contents of this output to the site support: $AMS_SITE_SUPPORT" >&2
     echo "" >&2
-    rm -f "$AMS_HOST_CACHE" 2> /dev/null
     exit 1
 fi
 
@@ -148,7 +155,6 @@ if [ $? -ne 0 ]; then
     echo " >>> ERROR: Unable to add the 'abs-rsync' module!" >&2
     echo "            Please send contents of this output to the site support: $AMS_SITE_SUPPORT" >&2
     echo "" >&2
-    rm -f "$AMS_HOST_CACHE" 2> /dev/null
     exit 1
 fi
 
@@ -157,7 +163,6 @@ if ! [ -e "$ABS_RSYNC" ]; then
     echo " >>> ERROR: '$ABS_RSYNC' is not executable!" >&2
     echo "            Please send contents of this output to the site support: $AMS_SITE_SUPPORT" >&2
     echo "" >&2
-    rm -f "$AMS_HOST_CACHE" 2> /dev/null
     exit 1
 fi
 
@@ -177,7 +182,6 @@ if ! [ -d "$ABS_ROOT" ]; then
     echo "" >&2
     echo " >>> ERROR: The ABS_ROOT directory does not exist!" >&2
     echo "" >&2
-    rm -f "$AMS_HOST_CACHE" 2> /dev/null
     exit 1
 fi
 
diff --git a/share/scripts/abs-go b/share/scripts/abs-go
--- a/share/scripts/abs-go
+++ b/share/scripts/abs-go
@@ -35,11 +35,18 @@ case "$INF_GO_JOB_NAME" in
            [ -n "$INF_GO_UMASK" ] && [ -n "$INF_GO_AGENT_MODULE" ] && \
            [ -n "$INF_GO_MAIN_NODE" ] && [ -n "$INF_GO_JOB_KEY" ]; then
             LC_SSH_AMS_IGNORE_SITE_INIT=Y ssh -t -X $INF_SSH_OPTIONS "$INF_GO_MAIN_NODE" " \
-                if [ -z \"\$AMS_ROOT\" ]; then \
+                if [ -z \"\$AMS_ROOT_V9\" ]; then \
                     if [ -f \"$INF_GO_BOOT_SCRIPT\" ]; then \
                         source \"$INF_GO_BOOT_SCRIPT\"; \
                     fi; \
                 fi; \
+                if [ -z \"\$AMS_ROOT_V9\" ]; then \
+                    echo \"\" >&2; \
+                    echo \" >>> ERROR: Advanced Module System (AMS) is not available!\" >&2; \
+                    echo \"            Please send contents of this output to the site support: $AMS_SITE_SUPPORT\" >&2; \
+                    echo \"\" >&2; \
+                    exit 1; \
+                fi
                 export INF_GO_SITE=\"$INF_GO_SITE\"; \
                 export INF_GO_UMASK=\"$INF_GO_UMASK\"; \
                 site --force init; \
diff --git a/share/scripts/abs-go-remote b/share/scripts/abs-go-remote
--- a/share/scripts/abs-go-remote
+++ b/share/scripts/abs-go-remote
@@ -17,10 +17,18 @@ INF_AMS_SITE_EMODS=$INF_GO_EXPORTED_MODULES_1
 INF_JOB_EMODS=$INF_GO_EXPORTED_MODULES_2
 
 # activate bash profile
-if [ -z "$AMS_ROOT" ]; then
+if [ -z "$AMS_ROOT_V9" ]; then
     if [ -f "$INF_GO_BOOT_SCRIPT" ]; then
         source "$INF_GO_BOOT_SCRIPT"
     fi
+fi
+
+if [ -z "$AMS_ROOT_V9" ]; then
+    echo "" >&2
+    echo " >>> ERROR: Advanced Module System (AMS) is not available!" >&2
+    echo "            Please send contents of this output to the site support: $AMS_SITE_SUPPORT" >&2
+    echo "" >&2
+    exit 1
 fi
 
 site --force init
