submit

diff --git a/share/scripts/abs-execution-script-L0 b/share/scripts/abs-execution-script-L0
--- a/share/scripts/abs-execution-script-L0
+++ b/share/scripts/abs-execution-script-L0
@@ -33,36 +33,98 @@ echo " Initial job information (recovered from transmitted environment):"
 echo "--------------------------------------------------------------------------------"
 echo " Job name             : $INF_JOB_NAME"
 echo " Job name suffix      : $INF_JOB_NAME_SUFFIX"
-echo " Job input path       : $INF_JOB_PATH"
 echo " Job input machine    : $INF_JOB_MACHINE"
+echo " Job input path       : $INF_JOB_PATH"
+echo " Job storage machine  : $INF_STORAGE_MACHINE"
+echo " Job storage path     : $INF_STORAGE_PATH"
+echo " Data IN copy mode    : $INF_DATAIN"
+echo " Data OUT copy mode   : $INF_DATAOUT"
 echo " Job key              : $INF_JOB_KEY"
-echo " ABS Root             : $ABS_ROOT"
 echo "------------------------------------------------------"
 echo " Hostname             : `hostname -f`"
 echo " Site support         : $AMS_SITE_SUPPORT"
 echo " Site ID              : $INF_SITE_ID"
 echo " ABS module version   : $INF_ABS_VERSION"
+echo " ABS Root             : $ABS_ROOT"
 echo " AMS boot script      : $INF_BOOT_SCRIPT"
-echo " User group           : $INF_UGROUP"
-echo " Umask                : $INF_UMASK"
 echo ""
 
+echo ""
 echo "#-------------------------------------------------------------------------------"
-echo "# L0.0 Booting into the first execution layer ..."
+echo "# L0 First execution layer ..."
 echo "#-------------------------------------------------------------------------------"
-# set umask
-echo ">>> Setting umask: $INF_UMASK"
-umask "0$INF_UMASK"
 
-# run under different group?
-if [ "$INF_UGROUP" != "`id -ng`" ]; then
-    echo ">>> Entering new user group: $INF_UGROUP"
-    echo ""
-    sg "$INF_UGROUP" -c "$ABS_ROOT/share/scripts/abs-execution-script-L0.1"
-else
-    echo ">>> Keeping current user group: `id -ng`"
-    $ABS_ROOT/share/scripts/abs-execution-script-L0.1
+# boot AMS ---------------------------------------------------------------------
+echo "User identity ..."
+echo "UID   : `id`"
+echo "Umask : `umask`"
+echo
+
+if [ -f "$INF_BOOT_SCRIPT" ]; then
+    # boot AMS system
+    source $INF_BOOT_SCRIPT
 fi
+
+echo "$ site -v activate $INF_SITE_ID"
+
+site -v activate $INF_SITE_ID
+
+if [ $? -ne 0 ]; then
+    echo "" >&2
+    echo " ERROR: Unable to activate site ($INF_SITE_ID)!" >&2
+    echo "        Please send contents of this file to the site support: $AMS_SITE_SUPPORT" >&2
+    echo "" >&2
+    exit 1
+fi
+
+# destroy ams host cache
+echo "$ ams-host --nocache"
+
+ams-host --nocache
+
+echo "$ amsmodule --system add abs:$INF_ABS_VERSION"
+
+# here we should use the same version as it was used for job submision
+amsmodule --system add abs:$INF_ABS_VERSION
+
+if [ $? -ne 0 ]; then
+    echo "" >&2
+    echo " ERROR: Unable to add 'abs:$INF_MODULE_VERS' module!" >&2
+    echo "        Please send contents of this file to the site support: $AMS_SITE_SUPPORT" >&2
+
+    echo "" >&2
+    exit 1
+fi
+
+# =============================================================================
+# Stage 01 - execute wrapper script +++++++++++++++++++++++++++++++++++++++++++
+# =============================================================================
+
+# Restore job environment ...
+source $ABS_ROOT/share/scripts/abs-execution-script-L1
+if [ $? -ne 0 ]; then exit 1; fi
+
+# Prepare working directory ...
+source $ABS_ROOT/share/scripts/abs-execution-script-L2
+if [ $? -ne 0 ]; then exit 1; fi
+
+# Copy input job data ...
+$ABS_ROOT/share/scripts/abs-execution-script-L3
+if [ $? -ne 0 ]; then exit 1; fi
+
+# Start job ...
+source $ABS_ROOT/share/scripts/abs-execution-script-L4
+if [ $? -ne 0 ]; then exit 1; fi
+
+# Sync data ...
+$ABS_ROOT/share/scripts/abs-execution-script-L5
+if [ $? -ne 0 ]; then exit 1; fi
+
+# Clean ...
+$ABS_ROOT/share/scripts/abs-execution-script-L6
+if [ $? -ne 0 ]; then exit 1; fi
+
+# =============================================================================
 
 echo
 echo "################################################################################"
diff --git a/share/scripts/abs-execution-script-L1 b/share/scripts/abs-execution-script-L1
--- a/share/scripts/abs-execution-script-L1
+++ b/share/scripts/abs-execution-script-L1
@@ -15,9 +15,6 @@ echo ""
 echo "# ------------------------------------------------------------------------------"
 echo "# L1: Restore job environment ..."
 echo "# ------------------------------------------------------------------------------"
-echo "User identity ..."
-echo "UID   : `id`"
-echo "Umask : `umask`"
 echo
 
 echo " Current directory  : `pwd` (Not used in restore process.)"
@@ -26,7 +23,7 @@ echo " Current directory  : `pwd` (Not used in restore process.)"
 export TMPDIR=`$ABS_ROOT/sbin/abs-get-setup-item INF_TMP_DIR`
 
 if [ $? -ne 0 ]; then
-    return 1
+    exit 1
 fi
 
 export INF_WHOLE_NAME="${INF_JOB_NAME}${INF_JOB_NAME_SUFFIX}"
@@ -54,19 +51,25 @@ export _TNAME_="$$.$USER"
 
 if [ "$INF_REMOTE_JOBDIR" == "NO" ]; then
     cp "$INF_JOB_PATH/${INF_WHOLE_NAME}.info" "$TMPDIR/${_TNAME_}.info"
+    if [ $? -ne 0 ]; then
+        echo ""  >&2
+        echo " ERROR: Unable to get the job info file!"  >&2
+        echo "        Source      : '$INF_JOB_PATH/${INF_WHOLE_NAME}.info'"  >&2
+        echo "        Destination : '$TMPDIR/${_TNAME_}.info'" >&2
+        echo "" >&2
+        exit 1
+    fi
 else
     /usr/bin/scp -o "StrictHostKeyChecking=no" \
-        "$INF_JOB_MACHINE:$INF_JOB_PATH/${INF_WHOLE_NAME}.info" "$TMPDIR/${_TNAME_}.info"
-fi
-
-if [ $? -ne 0 ]; then
-    echo ""  >&2
-    echo " ERROR: Unable to get the job info file!"  >&2
-    echo "        Source machine: '$INF_JOB_MACHINE'"  >&2
-    echo "        Source file   : '$INF_JOB_PATH/${INF_WHOLE_NAME}.info'"  >&2
-    echo "        Dest file     : '$TMPDIR/${_TNAME_}.info'" >&2
-    echo "" >&2
-    return 1
+        "$INF_STORAGE_MACHINE:$INF_STORAGE_PATH/${INF_WHOLE_NAME}.info" "$TMPDIR/${_TNAME_}.info"
+    if [ $? -ne 0 ]; then
+        echo ""  >&2
+        echo " ERROR: Unable to get the job info file!"  >&2
+        echo "        Source      : '$INF_STORAGE_MACHINE:$INF_STORAGE_PATH/${INF_WHOLE_NAME}.info'"  >&2
+        echo "        Destination : '$TMPDIR/${_TNAME_}.info'" >&2
+        echo "" >&2
+        exit 1
+    fi
 fi
 
 # ------------------------------------------------------------------------------
@@ -79,16 +82,16 @@ eval $EVAL_STRING
 
 if [ $? -ne 0 ] || [ $ABS_EXIT_CODE != "0" ]; then
     rm -f "$TMPDIR/${_TNAME_}.info"
-    return 1
+    exit 1
 fi
 
 # ------------------------------------------------------------------------------
 # AMS/ABS co-operation
 
 #FIXME
-export AMS_NCPU=$PBS_NCPUS
+export AMS_NCPU=$INF_NCPU
 export AMS_NGPU=$INF_NGPU
-export AMS_NNODE=$PBS_NCPUS
+export AMS_NNODE=$INF_NNODE
 export INF_NODEFILE=$PBS_NODEFILE
 export AMS_NODEFILE=$INF_NODEFILE
 
diff --git a/share/scripts/abs-execution-script-L2 b/share/scripts/abs-execution-script-L2
--- a/share/scripts/abs-execution-script-L2
+++ b/share/scripts/abs-execution-script-L2
@@ -17,22 +17,17 @@ echo ""
 echo "# ------------------------------------------------------------------------------"
 echo "# L2.1: Resources files ..."
 echo "# ------------------------------------------------------------------------------"
-echo "User identity ..."
-echo "UID   : `id`"
-echo "Umask : `umask`"
 echo
 
 
 # we need PBS_NODEFILE if it does not exist we create placebo with hostname
-# this happen on condor queue systems or when pstart is used
 
 if ! [ -f "$PBS_NODEFILE" ]; then
-    PBS_NODEFILE=$TMPDIR/pbs_nodes_placebo.${_TNAME_}
-    export PBS_NODEFILE_REMOVE=1
-    export PBS_NODEFILE
-    for((I=0;I<$INF_NCPU;I++)); do
-        hostname -f >> "$PBS_NODEFILE"
-    done
+    echo ""  >&2
+    echo " ERROR: PBS_NODEFILE does not exist!"  >&2
+    echo "        File path : '$PBS_NODEFILE'"  >&2
+    echo "" >&2
+    exit 1
 fi
 
 echo ""
@@ -77,7 +72,7 @@ echo ""
 echo "# ------------------------------------------------------------------------------"
 echo "# L2.2: Prepare working directory ..."
 echo "# ------------------------------------------------------------------------------"
-echo " Sync mode          : $INF_SYNC_MODE"
+echo " Data IN copy mode  : $INF_DATAIN"
 export INF_MAIN_NODE=`hostname -f`
 echo " Main node          : $INF_MAIN_NODE"
 echo " Job ID             : $INF_JOB_ID"
@@ -86,26 +81,12 @@ echo " Scratch type       : $INF_SCRATCH_TYPE"
 # ------------------------------------------------------------------------------
 # set working directory
 
-case $INF_SYNC_MODE in
-    jobdir)
-        INF_WORK_DIR=$INF_JOB_PATH
-        if [ "$INF_REMOTE_JOBDIR" == "YES" ]; then
-            echo "" >&2
-            echo " ERROR: The job input directory must be available locally on the computational node" >&2
-            echo "        if the 'jobdir' synchronization mode is used!" >&2
-            echo "" >&2
-            return 1
-        fi
-    ;;
-    sync | nosync )
-        INF_WORK_DIR="`$ABS_ROOT/sbin/abs-get-work-dir --type main $INF_WORK_DIR_TYPE`"
-        echo " Scratch dir        : $INF_WORK_DIR"
-        if [ $? -ne -0 ]; then
-            return 1
-        fi
-        INF_WORK_DIR="`eval echo "$INF_WORK_DIR"`"
-    ;;
-esac
+INF_WORK_DIR="`$ABS_ROOT/sbin/abs-get-work-dir --type main $INF_WORK_DIR_TYPE`"
+echo " Scratch dir        : $INF_WORK_DIR"
+if [ $? -ne -0 ]; then
+    return 1
+fi
+INF_WORK_DIR="`eval echo "$INF_WORK_DIR"`"
 
 echo " Working directory  : $INF_WORK_DIR"
 echo ""
@@ -113,15 +94,15 @@ echo ""
 # ------------------------------------------------------------------------------
 # create working directories if necessary
 
-case $INF_SYNC_MODE in
-    jobdir)
+case $INF_DATAIN in
+    keep)
         echo ">>> $INF_MAIN_NODE:$INF_WORK_DIR ---"
         timeout 30 df -h
         if [ $? -ne 0 ]; then
             echo ">>> WARNING: df command was not completed due to error or timeout."
         fi
     ;;
-    sync | nosync )
+    copy)
         echo " Create working directories on nodes:"
         for NODE_NAME in `cat $PBS_NODEFILE | sort -u`; do
             echo ""
@@ -132,7 +113,7 @@ case $INF_SYNC_MODE in
                 echo "" >&2
                 echo " ERROR: Unable to create the working directory on the specified node!" >&2
                 echo "" >&2
-                return 1
+                exit 1
             fi
         done
     ;;
@@ -150,7 +131,7 @@ if [ $? -ne 0 ]; then
     echo "" >&2
     echo " ERROR: Unable to change the current directory to the working directory." >&2
     echo "" >&2
-    return 1
+    exit 1
 fi
 echo " Success."
 
@@ -193,7 +174,7 @@ if [ $? -ne 0 ]; then
     echo "" >&2
     echo " ERROR: Unable to move the job info file into the working directory!" >&2
     echo "" >&2
-    return 1
+    exit 1
 fi
 
 # ------------------------------------------------------------------------------
@@ -208,17 +189,22 @@ if [ $? -ne 0 ]; then
     echo "" >&2
     echo " ERROR: Unable to update job status in the job info file!" >&2
     echo "" >&2
-    return 1
+    exit 1
 fi
 
-if [ "$INF_REMOTE_JOBDIR" == "NO" ]; then
-    if [ "$INF_SYNC_MODE" != "jobdir" ]; then
+case $INF_DATAIN in
+    copy)
+    if [ "$INF_REMOTE_JOBDIR" == "NO" ]; then
         cp "$INF_WORK_DIR/${INF_WHOLE_NAME}.info" "$INF_JOB_PATH/${INF_WHOLE_NAME}.info"
+    else
+        /usr/bin/scp -o "StrictHostKeyChecking=no" \
+            "$INF_WORK_DIR/${INF_WHOLE_NAME}.info" "$INF_STORAGE_MACHINE:$INF_STORAGE_PATH/${INF_WHOLE_NAME}.info"
     fi
-else
-    /usr/bin/scp -o "StrictHostKeyChecking=no" \
-        "$INF_WORK_DIR/${INF_WHOLE_NAME}.info" "$INF_JOB_MACHINE:$INF_JOB_PATH/${INF_WHOLE_NAME}.info"
-fi
+    echo "" >&2
+    echo " ERROR: Unable to update info file in the job input directory!" >&2
+    echo "" >&2
+    exit 1
+esac
 
 echo " Date = `date`"
 echo " Success."
@@ -228,15 +214,11 @@ echo "# ------------------------------------------------------------------------
 echo "# L2.3: Current node utilizations ..."
 echo "# ------------------------------------------------------------------------------"
 
-case $INF_SYNC_MODE in
-    jobdir | sync | nosync )
-        for NODE_NAME in `cat $INF_NODEFILE | sort -u`; do
-            echo ""
-            echo ">>> $NODE_NAME ----------------------------------"
-            ssh -x -o "StrictHostKeyChecking=no" $NODE_NAME "top -b -n 1"
-        done
-    ;;
-esac
+for NODE_NAME in `cat $INF_NODEFILE | sort -u`; do
+    echo ""
+    echo ">>> $NODE_NAME ----------------------------------"
+    ssh -x -o "StrictHostKeyChecking=no" $NODE_NAME "top -b -n 1"
+done
 
 echo ""
 echo "# ------------------------------------------------------------------------------"
diff --git a/share/scripts/abs-execution-script-L4 b/share/scripts/abs-execution-script-L4
--- a/share/scripts/abs-execution-script-L4
+++ b/share/scripts/abs-execution-script-L4
@@ -76,14 +76,19 @@ case $INF_JOB_NAME in
             return 1
         fi
 
-        if [ "$INF_REMOTE_JOBDIR" == "NO" ]; then
-            if [ "$INF_SYNC_MODE" != "jobdir" ]; then
+        case $INF_DATAIN in
+            copy)
+            if [ "$INF_REMOTE_JOBDIR" == "NO" ]; then
                 cp "$INF_WORK_DIR/${INF_WHOLE_NAME}.info" "$INF_JOB_PATH/${INF_WHOLE_NAME}.info"
+            else
+                /usr/bin/scp -o "StrictHostKeyChecking=no" \
+                    "$INF_WORK_DIR/${INF_WHOLE_NAME}.info" "$INF_STORAGE_MACHINE:$INF_STORAGE_PATH/${INF_WHOLE_NAME}.info"
             fi
-        else
-            /usr/bin/scp -o "StrictHostKeyChecking=no" \
-                "$INF_WORK_DIR/${INF_WHOLE_NAME}.info" "$INF_JOB_MACHINE:$INF_JOB_PATH/${INF_WHOLE_NAME}.info"
-        fi
+            echo "" >&2
+            echo " ERROR: Unable to update info file in the job input directory!" >&2
+            echo "" >&2
+            exit 1
+        esac
 
         # notify user if requested
         if [ -n "$INF_EMAIL" ]; then
