submit

diff --git a/share/scripts/abs-execution-script-L2 b/share/scripts/abs-execution-script-L2
--- a/share/scripts/abs-execution-script-L2
+++ b/share/scripts/abs-execution-script-L2
@@ -126,7 +126,7 @@ case $INF_SYNC_MODE in
         for NODE_NAME in `cat $PBS_NODEFILE | sort -u`; do
             echo ""
             echo ">>> $NODE_NAME:$INF_WORK_DIR ---"
-            ssh -o "StrictHostKeyChecking=no" $NODE_NAME "timeout 30 df -h; if [ \$? -ne 0 ]; then echo \">>> WARNING: df command was not completed due to error or timeout.\"; fi; mkdir -p $INF_WORK_DIR"
+            ssh -x -o "StrictHostKeyChecking=no" $NODE_NAME "timeout 30 df -h; if [ \$? -ne 0 ]; then echo \">>> WARNING: df command was not completed due to error or timeout.\"; fi; mkdir -p $INF_WORK_DIR"
 
             if [ $? -ne 0 ]; then
                 echo "" >&2
@@ -233,7 +233,7 @@ case $INF_SYNC_MODE in
         for NODE_NAME in `cat $INF_NODEFILE | sort -u`; do
             echo ""
             echo ">>> $NODE_NAME ----------------------------------"
-            ssh -o "StrictHostKeyChecking=no" $NODE_NAME "top -b -n 1"
+            ssh -x -o "StrictHostKeyChecking=no" $NODE_NAME "top -b -n 1"
         done
     ;;
 esac
diff --git a/share/scripts/abs-execution-script-L6 b/share/scripts/abs-execution-script-L6
--- a/share/scripts/abs-execution-script-L6
+++ b/share/scripts/abs-execution-script-L6
@@ -61,7 +61,7 @@ case $INF_SYNC_MODE in
         for NODE_NAME in `cat $PBS_NODEFILE | sort -u`; do
             echo ""
             echo ">>> $NODE_NAME:$INF_CLEAN_DIR ---"
-            ssh -o "StrictHostKeyChecking=no" $NODE_NAME "timeout 30 df -h; if [ \$? -ne 0 ]; then echo \">>> WARNING: df command was not completed due to error or timeout.\"; fi; rm -rf $INF_CLEAN_DIR"
+            ssh -x -o "StrictHostKeyChecking=no" $NODE_NAME "timeout 30 df -h; if [ \$? -ne 0 ]; then echo \">>> WARNING: df command was not completed due to error or timeout.\"; fi; rm -rf $INF_CLEAN_DIR"
         done
         ;;
     jobdir | nosync )
@@ -81,7 +81,7 @@ if [ -f "$IPC_SCRIPT" ]; then
     echo " Cleaning IPC stuff on nodes:"
     for NODE_NAME in `cat $PBS_NODEFILE | sort -u`; do
         echo "      $NODE_NAME"
-        ssh -o "StrictHostKeyChecking=no" $NODE_NAME "$IPC_SCRIPT"
+        ssh -x -o "StrictHostKeyChecking=no" $NODE_NAME "$IPC_SCRIPT"
     done
     echo " Success."
 fi
@@ -98,7 +98,7 @@ case $INF_SYNC_MODE in
         for NODE_NAME in `cat $PBS_NODEFILE | sort -u`; do
             echo ""
             echo ">>> $NODE_NAME ----------------------------------"
-            ssh -o "StrictHostKeyChecking=no" $NODE_NAME "top -b -n 1"
+            ssh -x -o "StrictHostKeyChecking=no" $NODE_NAME "top -b -n 1"
         done
     ;;
 esac
@@ -113,7 +113,7 @@ case $INF_SYNC_MODE in
         for NODE_NAME in `cat $PBS_NODEFILE | sort -u`; do
             echo ""
             echo ">>> $NODE_NAME ----------------------------------"
-            ssh -o "StrictHostKeyChecking=no" $NODE_NAME "uname -a; dmesg -T | tail -1000"
+            ssh -x -o "StrictHostKeyChecking=no" $NODE_NAME "uname -a; dmesg -T | tail -1000"
         done
     ;;
 esac
diff --git a/share/scripts/abs-execution-script-L6-ijobs b/share/scripts/abs-execution-script-L6-ijobs
--- a/share/scripts/abs-execution-script-L6-ijobs
+++ b/share/scripts/abs-execution-script-L6-ijobs
@@ -56,7 +56,7 @@ for((ID=1;ID<=$NIJOBS;ID++)); do
             for NODE_NAME in `cat $INF_IJOB_NODEFILE | sort -u`; do
                 echo ""
                 echo "     >>> $NODE_NAME:$INF_IJOB_WORK_DIR"
-                ssh -o "StrictHostKeyChecking=no" $NODE_NAME "timeout 30 df -h; if [ \$? -ne 0 ]; then echo \">>> WARNING: df command was not completed due to error or timeout.\"; fi; rm -rf $INF_IJOB_WORK_DIR" | awk '{ printf("     %s\n",$0); }'
+                ssh -x -o "StrictHostKeyChecking=no" $NODE_NAME "timeout 30 df -h; if [ \$? -ne 0 ]; then echo \">>> WARNING: df command was not completed due to error or timeout.\"; fi; rm -rf $INF_IJOB_WORK_DIR" | awk '{ printf("     %s\n",$0); }'
             done
             ;;
         jobdir | nosync )
